### ISSUE TITLE
facing the fastlane issue while deploying to app store

### ISSUE THREAD

**Issue by chirayuchirag1** [microsoft/app-store-vsts-extension#296] opened 2022-11-24 08:31 UTC
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/microsoft/app-store-vsts-extension/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: here

**Enter Task Name**: here  

list here (V# not needed):  
https://github.com/microsoft/app-store-vsts-extension/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

##[debug]Exit code 1 received from tool '/usr/local/lib/ruby/gems/3.0.0/bin/fastlane'
2022-11-17T10:51:18.4383700Z ##[debug]STDIO streams have closed for tool '/usr/local/lib/ruby/gems/3.0.0/bin/fastlane'
2022-11-17T10:51:18.4403470Z ##[debug]task result: Failed
2022-11-17T10:51:18.4444580Z ##[error]Error: The process '/usr/local/lib/ruby/gems/3.0.0/bin/fastlane' failed with exit code 1
2022-11-17T10:51:18.4457620Z ##[debug]Processed: ##vso[task.issue type=error;]Error: The process '/usr/local/lib/ruby/gems/3.0.0/bin/fastlane' failed with exit code 1
2022-11-17T10:51:18.4462100Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: The process '/usr/local/lib/ruby/gems/3.0.0/bin/fastlane' failed with exit code 1
2022-11-17T10:51:18.4466970Z ##[section]Finishing: Publish to the App Store
![error](https://user-images.githubusercontent.com/91462762/203731926-0d3a1a23-3b95-43ba-8d23-f1160c71876c.png)

**Comment by vmapetr** [comment] 2022-11-24 10:16
Hi @chirayuchirag1, thank you for the report!
Could you please provide a YAML pipeline template example and the complete log of the failed job?

**Comment by chirayuchirag1** [comment] 2022-11-24 16:11
Hi @vmapetr 
**this is the full log of the failed job**
--------------------------------------------------------------------------------------------------------
2022-11-22T06:22:42.4355300Z ##[debug]Using node path: /Users/runner/runners/2.213.2/externals/node10/bin/node
2022-11-22T06:22:42.7174720Z ##[debug]agent.TempDirectory=/Users/runner/work/_temp
2022-11-22T06:22:42.7245170Z ##[debug]loading inputs and endpoints
2022-11-22T06:22:42.7306080Z ##[debug]loading INPUT_AUTHTYPE
2022-11-22T06:22:42.7361390Z ##[debug]loading INPUT_SERVICEENDPOINT
2022-11-22T06:22:42.7393110Z ##[debug]loading INPUT_APIKEYINHOUSE
2022-11-22T06:22:42.7434970Z ##[debug]loading INPUT_ISTWOFACTORAUTH
2022-11-22T06:22:42.7476880Z ##[debug]loading INPUT_RELEASETRACK
2022-11-22T06:22:42.7502730Z ##[debug]loading INPUT_DISTRIBUTEONLY
2022-11-22T06:22:42.7523700Z ##[debug]loading INPUT_APPIDENTIFIER
2022-11-22T06:22:42.7549990Z ##[debug]loading INPUT_APPTYPE
2022-11-22T06:22:42.7566500Z ##[debug]loading INPUT_IPAPATH
2022-11-22T06:22:42.7572060Z ##[debug]loading INPUT_SKIPBINARYUPLOAD
2022-11-22T06:22:42.7573670Z ##[debug]loading INPUT_UPLOADMETADATA
2022-11-22T06:22:42.7575260Z ##[debug]loading INPUT_METADATAPATH
2022-11-22T06:22:42.7576870Z ##[debug]loading INPUT_UPLOADSCREENSHOTS
2022-11-22T06:22:42.7578430Z ##[debug]loading INPUT_SCREENSHOTSPATH
2022-11-22T06:22:42.7580160Z ##[debug]loading INPUT_SHOULDSUBMITFORREVIEW
2022-11-22T06:22:42.7581740Z ##[debug]loading INPUT_SHOULDAUTORELEASE
2022-11-22T06:22:42.7583280Z ##[debug]loading INPUT_RELEASENOTES
2022-11-22T06:22:42.7584870Z ##[debug]loading INPUT_SHOULDSKIPWAITINGFORPROCESSING
2022-11-22T06:22:42.7586490Z ##[debug]loading INPUT_SHOULDSKIPSUBMISSION
2022-11-22T06:22:42.7588070Z ##[debug]loading INPUT_DISTRIBUTEDTOEXTERNALTESTERS
2022-11-22T06:22:42.7589690Z ##[debug]loading INPUT_APPSPECIFICID
2022-11-22T06:22:42.7591450Z ##[debug]loading INPUT_INSTALLFASTLANE
2022-11-22T06:22:42.7594380Z ##[debug]loading INPUT_FASTLANETOOLSVERSION
2022-11-22T06:22:42.7595950Z ##[debug]loading INPUT_FASTLANETOOLSSPECIFICVERSION
2022-11-22T06:22:42.7597470Z ##[debug]loading INPUT_FASTLANEARGUMENTS
2022-11-22T06:22:42.7599890Z ##[debug]loading ENDPOINT_AUTH_1998c9cb-8a63-4517-99eb-e835ee58f5fc
2022-11-22T06:22:42.7602350Z ##[debug]loading ENDPOINT_AUTH_SCHEME_1998c9cb-8a63-4517-99eb-e835ee58f5fc
2022-11-22T06:22:42.7604530Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_1998c9cb-8a63-4517-99eb-e835ee58f5fc_USERNAME
2022-11-22T06:22:42.7606610Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_1998c9cb-8a63-4517-99eb-e835ee58f5fc_PASSWORD
2022-11-22T06:22:42.7607880Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2022-11-22T06:22:42.7609440Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2022-11-22T06:22:42.7611040Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2022-11-22T06:22:42.7613440Z ##[debug]loading SECRET_APP_ID_STAGING
2022-11-22T06:22:42.7614990Z ##[debug]loading SECRET_APP_ID_QA
2022-11-22T06:22:42.7616440Z ##[debug]loading SECRET_APP_ID_DEV
2022-11-22T06:22:42.7618050Z ##[debug]loading SECRET_FIREBASE_TOKEN
2022-11-22T06:22:42.7619170Z ##[debug]loaded 36
2022-11-22T06:22:42.7620580Z ##[debug]Agent.ProxyUrl=undefined
2022-11-22T06:22:42.7622200Z ##[debug]Agent.CAInfo=undefined
2022-11-22T06:22:42.7624420Z ##[debug]Agent.ClientCert=undefined
2022-11-22T06:22:42.7626610Z ##[debug]Agent.SkipCertValidation=undefined
2022-11-22T06:22:42.7628920Z ##[debug]check path : /Users/runner/work/_tasks/AppStoreRelease_2e371150-da5e-11e5-83da-0943b1acc572/1.207.0/task.json
2022-11-22T06:22:42.7631300Z ##[debug]adding resource file: /Users/runner/work/_tasks/AppStoreRelease_2e371150-da5e-11e5-83da-0943b1acc572/1.207.0/task.json
2022-11-22T06:22:42.7633390Z ##[debug]system.culture=en-US
2022-11-22T06:22:42.7634950Z ##[debug]authType=ServiceEndpoint
2022-11-22T06:22:42.7636930Z ##[debug]serviceEndpoint=1998c9cb-8a63-4517-99eb-e835ee58f5fc
2022-11-22T06:22:42.7639030Z ##[debug]1998c9cb-8a63-4517-99eb-e835ee58f5fc exists true
2022-11-22T06:22:42.7640760Z ##[debug]ipaPath=/Users/runner/work/r1/a/_occupant-ios-app/ios/occupant-prod.ipa
2022-11-22T06:22:42.7642400Z ##[debug]skipBinaryUpload=false
2022-11-22T06:22:42.7644380Z ##[debug]uploadMetadata=false
2022-11-22T06:22:42.7649700Z ##[debug]metadataPath=/Users/runner/work/r1/a
2022-11-22T06:22:42.7651400Z ##[debug]uploadScreenshots=false
2022-11-22T06:22:42.7653010Z ##[debug]screenshotsPath=/Users/runner/work/r1/a
2022-11-22T06:22:42.7661810Z ##[debug]releaseNotes=/Users/runner/work/r1/a
2022-11-22T06:22:42.7665800Z ##[debug]releaseTrack=TestFlight
2022-11-22T06:22:42.7667440Z ##[debug]shouldSkipWaitingForProcessing=false
2022-11-22T06:22:42.7668940Z ##[debug]shouldSubmitForReview=false
2022-11-22T06:22:42.7670480Z ##[debug]shouldAutoRelease=false
2022-11-22T06:22:42.7672050Z ##[debug]shouldSkipSubmission=false
2022-11-22T06:22:42.7673500Z ##[debug]teamId=undefined
2022-11-22T06:22:42.7675610Z ##[debug]teamName=undefined
2022-11-22T06:22:42.7677160Z ##[debug]distributeOnly=false
2022-11-22T06:22:42.7678690Z ##[debug]appBuildNumber=undefined
2022-11-22T06:22:42.7680210Z ##[debug]appSpecificId=1542951302
2022-11-22T06:22:42.7681680Z ##[debug]appType=iOS
2022-11-22T06:22:42.7683590Z ##[debug]installFastlane=true
2022-11-22T06:22:42.7702360Z ##[debug]fastlaneToolsVersion=LatestVersion
2022-11-22T06:22:42.7705580Z ##[debug]GEM_CACHE=undefined
2022-11-22T06:22:42.7708140Z ##[debug]gemCache=/Users/runner/.gem-cache
2022-11-22T06:22:42.7709840Z ##[debug]system.defaultWorkingDirectory=/Users/runner/work/r1/a
2022-11-22T06:22:42.7712250Z ##[debug]defaultRoot: '/Users/runner/work/r1/a'
2022-11-22T06:22:42.7714350Z ##[debug]findOptions.allowBrokenSymbolicLinks: 'true'
2022-11-22T06:22:42.7716360Z ##[debug]findOptions.followSpecifiedSymbolicLink: 'true'
2022-11-22T06:22:42.7718250Z ##[debug]findOptions.followSymbolicLinks: 'true'
2022-11-22T06:22:42.7720290Z ##[debug]findOptions.skipMissingFiles: 'undefined'
2022-11-22T06:22:42.7722240Z ##[debug]matchOptions.debug: 'false'
2022-11-22T06:22:42.7724310Z ##[debug]matchOptions.nobrace: 'true'
2022-11-22T06:22:42.7726220Z ##[debug]matchOptions.noglobstar: 'false'
2022-11-22T06:22:42.7728160Z ##[debug]matchOptions.dot: 'true'
2022-11-22T06:22:42.7730030Z ##[debug]matchOptions.noext: 'false'
2022-11-22T06:22:42.7731810Z ##[debug]matchOptions.nocase: 'false'
2022-11-22T06:22:42.7733680Z ##[debug]matchOptions.nonull: 'false'
2022-11-22T06:22:42.7735580Z ##[debug]matchOptions.matchBase: 'false'
2022-11-22T06:22:42.7737510Z ##[debug]matchOptions.nocomment: 'false'
2022-11-22T06:22:42.7739820Z ##[debug]matchOptions.nonegate: 'false'
2022-11-22T06:22:42.7742260Z ##[debug]matchOptions.flipNegate: 'false'
2022-11-22T06:22:42.7745200Z ##[debug]pattern: '/Users/runner/work/r1/a/_occupant-ios-app/ios/occupant-prod.ipa'
2022-11-22T06:22:42.7747350Z ##[debug]findPath: '/Users/runner/work/r1/a/_occupant-ios-app/ios/occupant-prod.ipa'
2022-11-22T06:22:42.7749980Z ##[debug]statOnly: 'true'
2022-11-22T06:22:43.3696900Z ##[debug]found 1 paths
2022-11-22T06:22:43.3700380Z ##[debug]applying include pattern
2022-11-22T06:22:43.3702520Z ##[debug]1 matches
2022-11-22T06:22:43.3704890Z ##[debug]1 final results
2022-11-22T06:22:43.3708150Z ##[debug]Checking for ruby install...
2022-11-22T06:22:43.3711310Z ##[debug]which 'ruby'
2022-11-22T06:22:43.3714190Z ##[debug]found: '/usr/local/opt/ruby@3.0/bin/ruby'
2022-11-22T06:22:43.3715980Z ##[debug]Installing fastlane...
2022-11-22T06:22:43.3718300Z ##[debug]which 'gem'
2022-11-22T06:22:43.3720640Z ##[debug]found: '/usr/local/opt/ruby@3.0/bin/gem'
2022-11-22T06:22:43.3723000Z ##[debug]which '/usr/local/opt/ruby@3.0/bin/gem'
2022-11-22T06:22:43.3725660Z ##[debug]found: '/usr/local/opt/ruby@3.0/bin/gem'
2022-11-22T06:22:43.3726970Z ##[debug]/usr/local/opt/ruby@3.0/bin/gem arg: ["install","fastlane"]
2022-11-22T06:22:43.3728140Z ##[debug]exec tool: /usr/local/opt/ruby@3.0/bin/gem
2022-11-22T06:22:43.3729210Z ##[debug]arguments:
2022-11-22T06:22:43.3730230Z ##[debug]   install
2022-11-22T06:22:43.3731670Z ##[debug]   fastlane
2022-11-22T06:22:43.3732260Z [command]/usr/local/opt/ruby@3.0/bin/gem install fastlane
2022-11-22T06:23:12.9672780Z Successfully installed fastlane-2.211.0
2022-11-22T06:23:12.9674360Z Parsing documentation for fastlane-2.211.0
2022-11-22T06:23:12.9675070Z Installing ri documentation for fastlane-2.211.0
2022-11-22T06:23:12.9676280Z Done installing documentation for fastlane after 24 seconds
2022-11-22T06:23:12.9676730Z 1 gem installed
2022-11-22T06:23:13.0112290Z ##[debug]Exit code 0 received from tool '/usr/local/opt/ruby@3.0/bin/gem'
2022-11-22T06:23:13.0117060Z ##[debug]STDIO streams have closed for tool '/usr/local/opt/ruby@3.0/bin/gem'
2022-11-22T06:23:13.0166050Z ##[debug]Updating fastlane...
2022-11-22T06:23:13.0174990Z ##[debug]which 'gem'
2022-11-22T06:23:13.0186240Z ##[debug]found: '/usr/local/opt/ruby@3.0/bin/gem'
2022-11-22T06:23:13.0202590Z ##[debug]which '/usr/local/opt/ruby@3.0/bin/gem'
2022-11-22T06:23:13.0205100Z ##[debug]found: '/usr/local/opt/ruby@3.0/bin/gem'
2022-11-22T06:23:13.0222520Z ##[debug]/usr/local/opt/ruby@3.0/bin/gem arg: ["update","fastlane","-i","/Users/runner/.gem-cache"]
2022-11-22T06:23:13.0224730Z ##[debug]exec tool: /usr/local/opt/ruby@3.0/bin/gem
2022-11-22T06:23:13.0226230Z ##[debug]arguments:
2022-11-22T06:23:13.0228300Z ##[debug]   update
2022-11-22T06:23:13.0229660Z ##[debug]   fastlane
2022-11-22T06:23:13.0231460Z ##[debug]   -i
2022-11-22T06:23:13.0233090Z ##[debug]   /Users/runner/.gem-cache
2022-11-22T06:23:13.0233950Z [command]/usr/local/opt/ruby@3.0/bin/gem update fastlane -i /Users/runner/.gem-cache
2022-11-22T06:23:17.5746060Z Updating installed gems
2022-11-22T06:23:17.5785390Z Nothing to update
2022-11-22T06:23:17.5820050Z Gems already up-to-date: fastlane
2022-11-22T06:23:17.6333150Z ##[debug]Exit code 0 received from tool '/usr/local/opt/ruby@3.0/bin/gem'
2022-11-22T06:23:17.6370330Z ##[debug]STDIO streams have closed for tool '/usr/local/opt/ruby@3.0/bin/gem'
2022-11-22T06:23:17.6417820Z ##[debug]fastlaneArguments=fastlane env
2022-11-22T06:23:17.6432750Z ##[debug]which 'fastlane'
2022-11-22T06:23:17.6464300Z ##[debug]found: '/usr/local/lib/ruby/gems/3.0.0/bin/fastlane'
2022-11-22T06:23:17.6582220Z ##[debug]externalTestersGroups=undefined
2022-11-22T06:23:17.6623060Z ##[debug]appIdentifier=com.smartinnovation75f.userapp
2022-11-22T06:23:17.6656950Z ##[debug]/usr/local/lib/ruby/gems/3.0.0/bin/fastlane arg: ["pilot","upload","-u","***"]
2022-11-22T06:23:17.6754990Z ##[debug]/usr/local/lib/ruby/gems/3.0.0/bin/fastlane arg: ["-i","/Users/runner/work/r1/a/_occupant-ios-app/ios/occupant-prod.ipa"]
2022-11-22T06:23:17.6869990Z ##[debug]/usr/local/lib/ruby/gems/3.0.0/bin/fastlane arg: ["-a","com.smartinnovation75f.userapp"]
2022-11-22T06:23:17.6945670Z ##[debug]/usr/local/lib/ruby/gems/3.0.0/bin/fastlane arg: ["-p","1542951302"]
2022-11-22T06:23:17.6997800Z ##[debug]distributedToExternalTesters=false
2022-11-22T06:23:17.7030290Z ##[debug]/usr/local/lib/ruby/gems/3.0.0/bin/fastlane arg: fastlane env
2022-11-22T06:23:17.7082290Z ##[debug]exec tool: /usr/local/lib/ruby/gems/3.0.0/bin/fastlane
2022-11-22T06:23:17.7151250Z ##[debug]arguments:
2022-11-22T06:23:17.7211500Z ##[debug]   pilot
2022-11-22T06:23:17.7246650Z ##[debug]   upload
2022-11-22T06:23:17.7248700Z ##[debug]   -u
2022-11-22T06:23:17.7265710Z ##[debug]   ***
2022-11-22T06:23:17.7305000Z ##[debug]   -i
2022-11-22T06:23:17.7347700Z ##[debug]   /Users/runner/work/r1/a/_occupant-ios-app/ios/occupant-prod.ipa
2022-11-22T06:23:17.7381940Z ##[debug]   -a
2022-11-22T06:23:17.7512820Z ##[debug]   com.smartinnovation75f.userapp
2022-11-22T06:23:17.7608180Z ##[debug]   -p
2022-11-22T06:23:17.7647510Z ##[debug]   1542951302
2022-11-22T06:23:17.7671940Z ##[debug]   fastlane
2022-11-22T06:23:17.7716850Z ##[debug]   env
2022-11-22T06:23:17.7757920Z [command]/usr/local/lib/ruby/gems/3.0.0/bin/fastlane pilot upload -u *** -i /Users/runner/work/r1/a/_occupant-ios-app/ios/occupant-prod.ipa -a com.smartinnovation75f.userapp -p 1542951302 fastlane env
2022-11-22T06:23:19.6842610Z [06:23:19]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
2022-11-22T06:23:22.2446250Z [06:23:22]: Sending anonymous analytics information
2022-11-22T06:23:22.2516680Z [06:23:22]: Learn more at https://docs.fastlane.tools/#metrics
2022-11-22T06:23:22.2529130Z [06:23:22]: No personal or sensitive data is sent.
2022-11-22T06:23:22.2530250Z [06:23:22]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
2022-11-22T06:23:22.2959830Z [06:23:22]: Ready to upload new build to TestFlight (App: 1542951302)...
2022-11-22T06:23:22.3234740Z 
2022-11-22T06:23:22.3236290Z Looking for related GitHub issues on fastlane/fastlane...
2022-11-22T06:23:22.3236600Z 
2022-11-22T06:23:22.4786230Z Found no similar issues. To create a new issue, please visit:
2022-11-22T06:23:22.4791620Z https://github.com/fastlane/fastlane/issues/new
2022-11-22T06:23:22.4797500Z Run `fastlane env` to append the fastlane environment to your issue
2022-11-22T06:23:22.4799920Z /usr/local/lib/ruby/gems/3.0.0/gems/rubyzip-2.3.2/lib/zip/central_directory.rb:164:in `read': [!] Is a directory @ io_fread - /Users/runner/work/r1/a/_occupant-ios-app/ios/occupant-prod.ipa (Errno::EISDIR)
2022-11-22T06:23:22.4802180Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/rubyzip-2.3.2/lib/zip/central_directory.rb:164:in `start_buf'
2022-11-22T06:23:22.4803590Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/rubyzip-2.3.2/lib/zip/central_directory.rb:132:in `read_from_stream'
2022-11-22T06:23:22.4805290Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/rubyzip-2.3.2/lib/zip/file.rb:92:in `block in initialize'
2022-11-22T06:23:22.4806950Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/rubyzip-2.3.2/lib/zip/file.rb:91:in `open'
2022-11-22T06:23:22.4808200Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/rubyzip-2.3.2/lib/zip/file.rb:91:in `initialize'
2022-11-22T06:23:22.4809380Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/rubyzip-2.3.2/lib/zip/file.rb:121:in `new'
2022-11-22T06:23:22.4810790Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/rubyzip-2.3.2/lib/zip/file.rb:121:in `open'
2022-11-22T06:23:22.4812890Z 	from /Users/runner/.gem-cache/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:68:in `fetch_info_plist_with_rubyzip'
2022-11-22T06:23:22.4816690Z 	from /Users/runner/.gem-cache/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:41:in `fetch_info_plist_file'
2022-11-22T06:23:22.4820840Z 	from /Users/runner/.gem-cache/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:32:in `fetch_app_platform'
2022-11-22T06:23:22.4822300Z 	from /Users/runner/.gem-cache/gems/fastlane-2.211.0/pilot/lib/pilot/manager.rb:85:in `fetch_app_platform'
2022-11-22T06:23:22.4823590Z 	from /Users/runner/.gem-cache/gems/fastlane-2.211.0/pilot/lib/pilot/build_manager.rb:32:in `upload'
2022-11-22T06:23:22.4824950Z 	from /Users/runner/.gem-cache/gems/fastlane-2.211.0/pilot/lib/pilot/commands_generator.rb:67:in `block (2 levels) in run'
2022-11-22T06:23:22.4829870Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
2022-11-22T06:23:22.4830770Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
2022-11-22T06:23:22.4831750Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
2022-11-22T06:23:22.4834630Z 	from /Users/runner/.gem-cache/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
2022-11-22T06:23:22.4836040Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
2022-11-22T06:23:22.4836970Z 	from /Users/runner/.gem-cache/gems/fastlane-2.211.0/pilot/lib/pilot/commands_generator.rb:167:in `run'
2022-11-22T06:23:22.4837900Z 	from /Users/runner/.gem-cache/gems/fastlane-2.211.0/pilot/lib/pilot/commands_generator.rb:19:in `start'
2022-11-22T06:23:22.4839870Z 	from /Users/runner/.gem-cache/gems/fastlane-2.211.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
2022-11-22T06:23:22.4840780Z 	from /Users/runner/.gem-cache/gems/fastlane-2.211.0/bin/fastlane:23:in `<top (required)>'
2022-11-22T06:23:22.4841480Z 	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
2022-11-22T06:23:22.4842110Z 	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<main>'
2022-11-22T06:23:22.4843160Z /usr/local/lib/ruby/gems/3.0.0/gems/rubyzip-2.3.2/lib/zip/central_directory.rb:164:in `read': Is a directory @ io_fread - /Users/runner/work/r1/a/_occupant-ios-app/ios/occupant-prod.ipa (Errno::EISDIR)
2022-11-22T06:23:22.4844230Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/rubyzip-2.3.2/lib/zip/central_directory.rb:164:in `start_buf'
2022-11-22T06:23:22.4846060Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/rubyzip-2.3.2/lib/zip/central_directory.rb:132:in `read_from_stream'
2022-11-22T06:23:22.4847050Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/rubyzip-2.3.2/lib/zip/file.rb:92:in `block in initialize'
2022-11-22T06:23:22.4847910Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/rubyzip-2.3.2/lib/zip/file.rb:91:in `open'
2022-11-22T06:23:22.4848720Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/rubyzip-2.3.2/lib/zip/file.rb:91:in `initialize'
2022-11-22T06:23:22.4849670Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/rubyzip-2.3.2/lib/zip/file.rb:121:in `new'
2022-11-22T06:23:22.4851090Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/rubyzip-2.3.2/lib/zip/file.rb:121:in `open'
2022-11-22T06:23:22.4852150Z 	from /Users/runner/.gem-cache/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:68:in `fetch_info_plist_with_rubyzip'
2022-11-22T06:23:22.4853260Z 	from /Users/runner/.gem-cache/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:41:in `fetch_info_plist_file'
2022-11-22T06:23:22.4855400Z 	from /Users/runner/.gem-cache/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:32:in `fetch_app_platform'
2022-11-22T06:23:22.4856420Z 	from /Users/runner/.gem-cache/gems/fastlane-2.211.0/pilot/lib/pilot/manager.rb:85:in `fetch_app_platform'
2022-11-22T06:23:22.4857490Z 	from /Users/runner/.gem-cache/gems/fastlane-2.211.0/pilot/lib/pilot/build_manager.rb:32:in `upload'
2022-11-22T06:23:22.4858460Z 	from /Users/runner/.gem-cache/gems/fastlane-2.211.0/pilot/lib/pilot/commands_generator.rb:67:in `block (2 levels) in run'
2022-11-22T06:23:22.4859980Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
2022-11-22T06:23:22.4860820Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
2022-11-22T06:23:22.4861640Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
2022-11-22T06:23:22.4862930Z 	from /Users/runner/.gem-cache/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
2022-11-22T06:23:22.4864260Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
2022-11-22T06:23:22.4866090Z 	from /Users/runner/.gem-cache/gems/fastlane-2.211.0/pilot/lib/pilot/commands_generator.rb:167:in `run'
2022-11-22T06:23:22.4867930Z 	from /Users/runner/.gem-cache/gems/fastlane-2.211.0/pilot/lib/pilot/commands_generator.rb:19:in `start'
2022-11-22T06:23:22.4869160Z 	from /Users/runner/.gem-cache/gems/fastlane-2.211.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
2022-11-22T06:23:22.4871060Z 	from /Users/runner/.gem-cache/gems/fastlane-2.211.0/bin/fastlane:23:in `<top (required)>'
2022-11-22T06:23:22.4871780Z 	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
2022-11-22T06:23:22.4872410Z 	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<main>'
2022-11-22T06:23:22.4960850Z ##[debug]Exit code 1 received from tool '/usr/local/lib/ruby/gems/3.0.0/bin/fastlane'
2022-11-22T06:23:22.4963780Z ##[debug]STDIO streams have closed for tool '/usr/local/lib/ruby/gems/3.0.0/bin/fastlane'
2022-11-22T06:23:22.4996080Z ##[debug]task result: Failed
2022-11-22T06:23:22.5037750Z ##[error]Error: The process '/usr/local/lib/ruby/gems/3.0.0/bin/fastlane' failed with exit code 1
2022-11-22T06:23:22.5050520Z ##[debug]Processed: ##vso[task.issue type=error;]Error: The process '/usr/local/lib/ruby/gems/3.0.0/bin/fastlane' failed with exit code 1
2022-11-22T06:23:22.5055630Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: The process '/usr/local/lib/ruby/gems/3.0.0/bin/fastlane' failed with exit code 1
2022-11-22T06:23:22.5063300Z ##[section]Finishing: Publish to the App Store 

-------------------------------------------------------------------------------------------------------------------------

steps:
- task: ms-vsclient.app-store.app-store-release.AppStoreRelease@1
  displayName: 'Publish to the App Store '
  inputs:
    serviceEndpoint: AppleAppStoreConnection
    appIdentifier: com.smartinnovation75f.userapp
    ipaPath: '$(System.DefaultWorkingDirectory)/_occupant-ios-app/ios/occupant-prod.ipa'
    appSpecificId: 1542951302
    fastlaneArguments: 'fastlane env'

**this is the YAML script**

**Comment by vmapetr** [comment] 2022-12-05 20:17
@chirayuchirag1 from the following error messages
```
2022-11-22T06:23:22.4799920Z /usr/local/lib/ruby/gems/3.0.0/gems/rubyzip-2.3.2/lib/zip/central_directory.rb:164:in read': [!] Is a directory @ io_fread - /Users/runner/work/r1/a/_occupant-ios-app/ios/occupant-prod.ipa (Errno::EISDIR)
...
````
It seems like ipaPath contains a directory and not an ipa file itself.

Could you please replace the arguments in the template, to get more extended verbose?
```
fastlaneArguments: 'fastlane env' ==> fastlaneArguments: '--capture_output' 
```
And in case you want to get the output of `fastlane env` please use it as a separate command instead of a command option.

**Comment by chirayuchirag1** [comment] 2022-12-06 12:36
Sure will try and update

**Comment by chirayuchirag1** [comment] 2022-12-13 07:18
I haven’t set up the appsepecificpassword variable there can you please guide me where to add it in the task?
***@***.***

**Comment by vmapetr** [comment] 2022-12-13 11:55
@chirayuchirag1 just add it to the AppStoreRelease task `inputs` in your template, e.g:
```
task: ms-vsclient.app-store.app-store-release.AppStoreRelease@1
displayName: 'Publish to the App Store '
inputs:
  serviceEndpoint: AppleAppStoreConnection
  appIdentifier: com.smartinnovation75f.userapp
  ipaPath: '$(System.DefaultWorkingDirectory)/_occupant-ios-app/ios/occupant-prod.ipa'
  appSpecificId: 1542951302
  fastlaneArguments: 'fastlane env'
  appSpecificPassword: '***'
```

**Comment by chirayuchirag1** [comment] 2022-12-13 13:20
And whatever inputs you are looking are provided by default

**Comment by vmapetr** [comment] 2022-12-13 22:43
@chirayuchirag1 sorry, but I cannot see any attached screenshots in Github.
The original issue with the path to the IPA file is not actual anymore, could you please open another ticket in this repo and copy your current YAML template and the error from logs there?

**Comment by chirayuchirag1** [comment] 2022-12-14 13:19
I have attached the screenshot and you can can see that I cant add any inputs

**Comment by vmapetr** [comment] 2022-12-15 21:16
@chirayuchirag1, please notice that attachments that were sent via email don't show in Github comments, so we cannot see any screenshots.
Since the original issue with the build failure caused by an incorrect IPA file path is resolved, I'm going to close this issue.
Could you please open another ticket for a current problem with the authorization, and attach the failure logs and a specified description of your pipeline if it was configured via the classic editor, or YAML template if it was configured via YAML. 
Thanks!

**Closed by vmapetr** 2022-12-15 21:16 UTC
Labels: bug, Area: AppStore
