### ISSUE TITLE
Failed find: ENOENT: no such file or directory, stat '/.app' in version 1.176.0

### ISSUE THREAD

**Issue by arnoldsi-tr** [microsoft/app-store-vsts-extension#177] opened 2020-10-04 14:03 UTC
Hi,
We are using Azure devops visual editor to deploy our iOS app to Apple store. Couple days ago we started to encounter the following error. 
We checked the difference with build versions and saw that "Apple App Store Release" updated from 1.175.0 to 1.176.0 which started to cause this issue:
`
2020-10-01T14:13:10.5816300Z ##[section]Starting: Publish to the App Store
2020-10-01T14:13:10.5869030Z ==============================================================================
2020-10-01T14:13:10.5869520Z Task         : Apple App Store Release
2020-10-01T14:13:10.5869940Z Description  : Release an app to TestFlight or the Apple App Store
2020-10-01T14:13:10.5870310Z Version      : 1.176.0
2020-10-01T14:13:10.5870620Z Author       : Microsoft Corporation
2020-10-01T14:13:10.5872120Z Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store)
2020-10-01T14:13:10.5872740Z ==============================================================================
2020-10-01T14:13:34.1386040Z ##[error]Error: Failed find: ENOENT: no such file or directory, stat '/Users/runner/work/r1/a/_my_app_wrapper/platforms/ios/build/device/myApp.app'
2020-10-01T14:13:34.1922400Z ##[section]Finishing: Publish to the App Store
`

This is very critical error to us.

**Comment by EzzhevNikita** [comment] 2020-10-05 15:50
Hi @arnoldsi-tr! Could please share some additional information for this issue:
1) Which type of agent are using (Private or MS hosted) ?
2) If you run you build on private agent try to execute the pipeline on MS hosted agent if it is possible.
2) Could you, please share the full log from this task with enabled system diagnostics?

**Comment by EzzhevNikita** [comment] 2020-10-12 08:54
Hi @arnoldsi-tr! Is this still actual for you?

**Comment by EzzhevNikita** [comment] 2020-10-22 09:51
Hi @arnoldsi-tr ! Do you still facing with this issue?

**Comment by EzzhevNikita** [comment] 2020-10-26 08:14
I'm closing this due to inactivity. Feel free to reopen it, if you still faced with this issue.

**Comment by yoandinkov** [comment] 2020-10-28 16:09
@EzzhevNikita 

I experienced the same error as @arnoldsi-tr . Our project was on hold during Q2 and Q3 and it's hard to determine, when this happened, but my last successful build was on 20.05.2020 

## Use case

We're using "Apple App Store Release" task to deploy an IPA generated file to TestFlight.

My pipeline is roughly like this:
- get sources
- install distribution cert
- install provisioning profile
- cordova platform
- cordova build
- **publish IPA to Test Flight**

About environment, we use privately run build agent (macos)
cordova-cli@9.0.0

platform params:
`cordova platform add ios@5.1.1`
build params:
`cordova build --release --device`

Apple App Store Release params:
application type: iOS
binary path: `**/*.ipa`
track: TestFlight

skip build processing: false
skip submission: false
distribute to external testers: false

## Actual problem

The problem is that all steps up until `publish IPA` are successful and I get a `** ARCHIVE SUCCEEDED **` and `** EXPORT SUCCEEDED **` in the build step, however in the next step, I get an NODE.JS exception that file ending on ".app" is not existent. (basically the same as in the original issue)

After some debugging and research, I have found out several things:
* you have updated findMatch `let paths: string[] = tl.findMatch('', ipaPath);`

Somewhere here, I believe Node.js fails. I believe that the build step generates an `*.app.dSYM` file that points to a non-existent `.app` file, thus node.js failing to find the .app file and crashing all together.

This is probably a new behavior of the updated `findMatch` method. For some reason, it iterates all files and not only `.ipa` ones and when it's symbolic it fails (for non-existent real file).

## Current solution

If I hardcode the path to the generated `.ipa` file, it works fine, as there is no glob pattern related and it not iterates symbolic links.

## Notes

As stated [here](https://github.com/apache/cordova-ios/issues/527), `cordova build` should not generate a `.app` file, so not sure why we have that '.app.dSYM' link file on first place.

Having to hardcode the path is not the optimal solution for me, so it will be nice if we can have some try/catch states on that. Not sure if this is easily reproducible and fixable by your team (as you probably do that in your free time). As it's probably OS related.

Tried with cordova-cli@10.0.0 and 8.1.2 with no avail. Wanted to try with ios@6.1.1 (latest), but some plugins were failing so couldn't reproduce it. However I don't believe it's an cordova bug per se, but more like node or findMatch problem.

I tried to find my node.js version in the logs, but couldn't do it, so will dig on that as well.

**Comment by EzzhevNikita** [comment] 2020-10-29 13:34
@yoandinkov Thank you for your feedback, as it is actual problem I reopen this issue! We will

**Comment by yoandinkov** [comment] 2020-10-30 21:34
Thank you @EzzhevNikita  for the quick reaction and already made PR, really appreciate it!

I will gladly test as soon as this is out and ready :)

**Comment by EzzhevNikita** [comment] 2020-11-02 09:04
@yoandinkov , the fix for this issue was merged. Fixed version should become available in Azure Devops within 4 weeks

**Closed** 2020-12-03 12:41 UTC
Labels: Task: AppStoreRelease, bug
