### ISSUE TITLE
How to provide submission_information

### ISSUE THREAD

**Issue by ScottMacDougall** [Microsoft/app-store-vsts-extension#103] opened 2018-11-21 19:36 UTC
Using the App Store Release task, I can't submit my app for review because the task timesout, as fastlane can't get past App Store Connect asking about Export Compliance and Advertising Identifier.

I had a look at this closed issue: https://github.com/Microsoft/app-store-vsts-extension/issues/32 which says adding submission_information as metadata works. I tried added submission_information.txt with a json string, and it doesn't work. Not sure if there's another format that is expected.

**Comment by ooikengsiang** [comment] 2018-11-23 04:45
For my case, I put them into the Deliverfile, just make sure the Deliverfile is formatted correctly and placed in the location where the fastlane can read.
See this: https://github.com/Microsoft/app-store-vsts-extension/issues/102

**Comment by madhurig** [comment] 2019-01-09 19:39
@ScottMacDougall - I hope @ooikengsiang 's suggestion helped you. Closing this since it is not a bug.

**Closed by madhurig** 2019-01-09 19:39 UTC

**Comment by hakanyildizay** [comment] 2019-03-08 11:47
@ooikengsiang & @ScottMacDougall 🙋‍♂️ 
I had the same problem. 
Where did you place your deliverfile? 

or is there a way to add these properties in vsts AppStore Release task?

Thank you 😊

**Comment by ooikengsiang** [comment] 2019-03-15 11:38
Sorry, totally skipped the email.
I created a folder name "fastlane" in my project.
Here is how I structure my project.

Project
 - fastlane
    - metadata
       - en-US
          - release_notes.txt
    - Deliverfile

**Comment by tipa** [comment] 2019-12-03 12:01
@ooikengsiang is the Deliverfile automatically recognized by fastlane when the Deliverfile is being places in that folder structure? Or what else did you have to do in order to point to it?

**Comment by hakanyildizay** [comment] 2019-12-07 18:27
@ooikengsiang no problem I did as you told. And It worked as expected.
@tipa you don't have to do any extra work. It is necessary to put it in that folder structure just like @ooikengsiang explained. Lastly to answer you last question even though you didn't address me,

1. You could use shell script tasks in your pipeline and according to your specific conditions you could generate your new Delivefile during pipeline. 

2. Also sometimes you have to remove it if you don't want to overwrite Fastlane deliver options by Deliverfile.

Bash script task:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/shell-script?view=azure-devops

Create a file using shell script,
https://www.cyberciti.biz/faq/create-a-file-in-linux-using-the-bash-shell-terminal/

Script should look more or less like this 
> echo "{content of Deliverfile}" > Deliverfile

**Comment by tipa** [comment] 2019-12-09 07:55
@hakanyildizay thanks for your response.
Unfortunately it doesn't work for me. I have the `Deliverfile` (without file ending) in a folder called `fastlane` which itself is in the repo root folder to be checked out during the pipeline (in the same folder that my ".sln" file is located.
These are the contents of the Deliverfile:
```
submission_information({  
  add_id_info_uses_idfa: true,
  add_id_info_serves_ads: true,
  add_id_info_tracks_install: false,
  add_id_info_tracks_action: false,
  add_id_info_limits_tracking: true
})
```

However, I still get this error
```
/Users/runner/.gem-cache/gems/fastlane-2.137.0/spaceship/lib/spaceship/tunes/tunes_client.rb:1194:in `send_app_submission': [!] Something wrong with your Ad ID information: ["ITC.apps.idfa.errorMessage.binaryviolatesterms"]. (RuntimeError)
	from /Users/runner/.gem-cache/gems/fastlane-2.137.0/spaceship/lib/spaceship/tunes/app_submission.rb:152:in `complete!'
	from /Users/runner/.gem-cache/gems/fastlane-2.137.0/deliver/lib/deliver/submit_for_review.rb:27:in `submit!'
	from /Users/runner/.gem-cache/gems/fastlane-2.137.0/deliver/lib/deliver/runner.rb:172:in `submit_for_review'
	from /Users/runner/.gem-cache/gems/fastlane-2.137.0/deliver/lib/deliver/runner.rb:50:in `run'
	from /Users/runner/.gem-cache/gems/fastlane-2.137.0/deliver/lib/deliver/commands_generator.rb:79:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/runner/.gem-cache/gems/fastlane-2.137.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/runner/.gem-cache/gems/fastlane-2.137.0/deliver/lib/deliver/commands_generator.rb:182:in `run'
	from /Users/runner/.gem-cache/gems/fastlane-2.137.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
	from /Users/runner/.gem-cache/gems/fastlane-2.137.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	from /Users/runner/.gem-cache/gems/fastlane-2.137.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `load'
	from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `<main>'
/Users/runner/.gem-cache/gems/fastlane-2.137.0/spaceship/lib/spaceship/tunes/tunes_client.rb:1194:in `send_app_submission': Something wrong with your Ad ID information: ["ITC.apps.idfa.errorMessage.binaryviolatesterms"]. (RuntimeError)
	from /Users/runner/.gem-cache/gems/fastlane-2.137.0/spaceship/lib/spaceship/tunes/app_submission.rb:152:in `complete!'
	from /Users/runner/.gem-cache/gems/fastlane-2.137.0/deliver/lib/deliver/submit_for_review.rb:27:in `submit!'
	from /Users/runner/.gem-cache/gems/fastlane-2.137.0/deliver/lib/deliver/runner.rb:172:in `submit_for_review'
	from /Users/runner/.gem-cache/gems/fastlane-2.137.0/deliver/lib/deliver/runner.rb:50:in `run'
	from /Users/runner/.gem-cache/gems/fastlane-2.137.0/deliver/lib/deliver/commands_generator.rb:79:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/runner/.gem-cache/gems/fastlane-2.137.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/runner/.gem-cache/gems/fastlane-2.137.0/deliver/lib/deliver/commands_generator.rb:182:in `run'
	from /Users/runner/.gem-cache/gems/fastlane-2.137.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
	from /Users/runner/.gem-cache/gems/fastlane-2.137.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	from /Users/runner/.gem-cache/gems/fastlane-2.137.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `load'
	from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `<main>'
##[error]Error: fastlane failed with return code: 1
```

What I am trying to achieve is not having to manually publish the update through iTunes Connect, which requires me to manually respond to the IDFA questions (I am using AdMob in my app)
![image](https://user-images.githubusercontent.com/2863198/70417424-7bd61900-1a61-11ea-86b4-1f8f51171019.png)

What am I doing wrong?

**Comment by hakanyildizay** [comment] 2019-12-10 17:38
Hi @tipa 
Actually your Deliverfile looks good.

However, I think, the name should also match with name: "Deliverfile" without extension.
>  I have the Deliverfile (without file ending)

You can see an example [here](https://docs.fastlane.tools/actions/deliver/#usage)
If It still does not work, please do not hesitate to ask :).

Btw to make some quick troubleshoot, I would recommend to try "[fastlane deliver](https://docs.fastlane.tools/actions/deliver/)" command on the actual machine that you are working on. Because using App Store tool can take longer than using local fastlane command.

**Comment by tipa** [comment] 2019-12-10 18:15
My Deliverfile was without extension - I don't know why it wasnt recognized...
I now decided to try your recommendation using a bash script and then it started working, likely because it writes the file to another location.
Script looks like this:
```
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo "submission_information({add_id_info_uses_idfa: true, add_id_info_serves_ads: true, add_id_info_tracks_install: false, add_id_info_tracks_action: false, add_id_info_limits_tracking: true })" > Deliverfile'
```

**Comment by hakanyildizay** [comment] 2019-12-16 14:41
Hi @tipa, 
So happy that you finally managed to work it out. 
But I am still surprised about why it couldn't recognize "Deliverfile". 
But one of the benefit of generating the Deliverfile at runtime during your devops pipeline is that no body in your development team can mistakenly delete or change the file content. :)
Happy new year 🥳

**Comment by ooikengsiang** [comment] 2019-12-16 14:48
By default, build pipeline only copy your the build package to artifact location. It doesn't copy the Deliverfile.
Release pipeline can't access the source code, it only have the access to whatever files in the artifact location.
You need to manually add a task to copy the Deliverfile and release_note to artifact location with the given folder structure.
