### ISSUE TITLE
Error uploading extension

### ISSUE THREAD

**Issue by DiMaReCas** [microsoft/app-store-vsts-extension#195] opened 2020-11-06 20:06 UTC
**Error:** Extension validation error

Task definition input 'skipBinaryUpload' and Task definition input 'ipaPath' must belong to same group as they are dependent inputs for Task with ID '2e371150-da5e-11e5-83da-0943b1acc572'.

**Azuredevops Version:** Dev17.M153.5

The error appears when trying to add the extension, the last successfully uploaded version was version 1.176.0, the error appears in the version 1.177.2 and 1.178.2

**Comment by PeterStaev** [comment] 2020-11-06 20:39
Getting the same error as well on a on-premise AzureDevOps Server 2020

**Comment by anatolybolshakov** [comment] 2020-11-07 14:41
Hi @DiMaReCas @PeterStaev we rolled out a fix for this issue - could you please check it with the last version?

**Comment by PeterStaev** [comment] 2020-11-07 15:19
Hey @anatolybolshakov I just tried to install 1.178.3 and I'm getting a slightly different error this time:
>Task definition input 'releaseTrack' and Task definition input 'appSpecificId' must belong to same group as they are dependent inputs for Task with ID '2e371150-da5e-11e5-83da-0943b1acc572'

**Comment by alexander-smolyakov** [comment] 2020-11-09 12:15
Hey, @PeterStaev could you please check and share your version of Azure DevOps 2020 Server. You can find the actual version of Azure DevOps from the "About" page or by the link:
`<server_domain>/DefaultCollection/_home/About`

Thanks!

**Comment by PeterStaev** [comment] 2020-11-09 14:39
@alexander-smolyakov , it is: `Version Dev18.M170.6`. This is an Azure DevOps Server 2020 RTW install.

**Comment by DiMaReCas** [comment] 2020-11-09 15:33
@anatolybolshakov  I tried with version 1.178.3 and I get the same message.

Extension validation error

Task definition input 'releaseTrack' and Task definition input 'appSpecificId' must belong to same group as they are dependent inputs for Task with ID '2e371150-da5e-11e5-83da-0943b1acc572'.

**Comment by alexander-smolyakov** [comment] 2020-11-10 13:40
@PeterStaev, @DiMaReCas the [PR](https://github.com/microsoft/app-store-vsts-extension/pull/198) with the fix was merged, it available with the release [v1.178.4](https://github.com/microsoft/app-store-vsts-extension/releases/tag/v1.178.4) of the extension.
I'm closing it at the moment - please feel free to reopen if the issue is still reproducible.

Thanks!

**Closed by alexander-smolyakov** 2020-11-10 13:40 UTC
Labels: Task: AppStoreRelease, awaiting deployment, bug
