### ISSUE TITLE
Task always uses gem installed in /usr/bin/gem instead of the one specified in PATH when Install Fastlane is selected

### ISSUE THREAD

**Issue by r2d2rigo** [microsoft/app-store-vsts-extension#141] opened 2020-02-26 11:51 UTC
This issue is related to #139, both caused by a fastlane update that bumped the minimum Ruby version to 2.4.0 while the one bundled with macOS Mojave is 2.3.7. This issue only happens when you want the task to automatically install fastlane for you - if you install Ruby and fastlane manually in the machine it works as expected.

I have installed Ruby 2.6.3 though rvm and verified that it works. I even tried updating the PATH with a bash script before running the publish task:

```
2020-02-26T11:41:17.5562500Z [command]/bin/bash --noprofile --norc /Users/xxx/vsts-agent-osx-x64-2.153.2/_work/_temp/c08682fe-fe8a-4e63-b201-9dba6071d341.sh
2020-02-26T11:41:17.5630900Z Current PATH
2020-02-26T11:41:17.5632410Z /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin
2020-02-26T11:41:17.5632850Z Gem location (which gem)
2020-02-26T11:41:17.5646940Z /usr/bin/gem
2020-02-26T11:41:17.7010480Z Updated PATH
2020-02-26T11:41:17.7012970Z /usr/local/opt/ruby/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin
2020-02-26T11:41:17.7013320Z Gem location (which gem)
2020-02-26T11:41:17.7036180Z /usr/local/opt/ruby/bin/gem
```

However, when the task runs, it still tries to run /usr/bin/gem instead of /usr/local/opt/ruby/bin/gem:

```
2020-02-26T11:41:18.0386060Z ==============================================================================
2020-02-26T11:41:18.0386150Z Task         : Apple App Store Release
2020-02-26T11:41:18.0386220Z Description  : Release an app to TestFlight or the Apple App Store
2020-02-26T11:41:18.0386330Z Version      : 1.158.0
2020-02-26T11:41:18.0386390Z Author       : Microsoft Corporation
2020-02-26T11:41:18.0386520Z Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store)
2020-02-26T11:41:18.0386620Z ==============================================================================
2020-02-26T11:41:18.1839790Z 6c94aa33-279e-4610-9c36-71e6fcfd2324 exists true
2020-02-26T11:41:18.1992630Z [command]/usr/bin/gem uninstall fastlane -a -I
```

**Comment by anatolybolshakov** [comment] 2020-09-07 13:21
Hi @r2d2rigo is issue still actual for you?

**Comment by anatolybolshakov** [comment] 2020-09-17 14:54
Hi @r2d2rigo please let us know if this issue is still actual for you

**Comment by r2d2rigo** [comment] 2020-09-21 10:56
Hi @anatolybolshakov, sorry but I don't have access to that pipeline anymore and can't check if it still happens.

**Comment by anatolybolshakov** [comment] 2020-09-22 10:20
@r2d2rigo ok, thanks! We can't reproduce this issue currently, I'm going to close it since we don't have repro steps here - please feel free to reopen it if you'll face with it again or will have a chance to reproduce it

**Closed by anatolybolshakov** 2020-09-22 10:20 UTC
Labels: Task: AppStoreRelease, bug
