### ISSUE TITLE
Cannot distribute TestFlight to testers

### ISSUE THREAD

**Issue by JKennedy24** [Microsoft/app-store-vsts-extension#71] opened 2017-06-07 09:09 UTC
Running the task to upload to testflight

click the button "distribute to external testers"

But this causes the task to fail with the error:

> n `handle_response': [!] {"code"=>"You must provide an answer for this question.", "description"=>"Failed to submit build for review."} (Spaceship::Client::UnexpectedResponse)

The UI for the extension provides no way to provide a "Description" so this feature does not work

**Comment by lkillgore** [comment] 2017-06-08 20:35
Hi @JKennedy24.  I found this answer from fastlane's forum https://github.com/fastlane/fastlane/issues/4002#issuecomment-218849799

By any chance did you see something that looks like this in your log?
```
TestFlight requires you to provide the answer to the encryption question
to provide the reply, please add the following to your Info.plist file

<key>ITSAppUsesNonExemptEncryption</key><false/>

Afterwards re-build your app and try again

```
It's seems this setting is incompatible with TestFlight, and using it will give the same error you're receiving.

**Comment by JKennedy24** [comment] 2017-06-09 07:54
I didn't see that message in the log. all I saw was the message posted above.

should I try adding the attribute you have posted to my info.plist to get it to work?

**Comment by lkillgore** [comment] 2017-06-09 12:46
Hmm... It's interesting that you're not getting that message.

Yes, I think you should consider trying it out.  (This link describes the implications: https://stackoverflow.com/questions/35739361/itsappusesnonexemptencryption-export-compliance-while-internal-testing)  Alternatively, (if this is the issue) it appears that there is a submission process to allow your app to use that feature.

Also, do you know which version of fastlane you're using?  If this is the issue and you're not getting the message I posted, I wonder if there may be a regression in fastlane or if the version you're using is out-of-date.

**Comment by JKennedy24** [comment] 2017-06-09 13:01
Thanks for the reply. I will try adding that key to my info.plist and try another release when I have an update and I will report back

**Comment by JKennedy24** [comment] 2017-06-29 16:32
I have added that to my info.plist and I now get the error:

> 2017-06-29T16:30:45.4636980Z [!] You must specify at least one group using the `:groups` option to distribute externally
> 2017-06-29T16:30:46.0587080Z ##[error]Error: fastlane failed with return code: 1

when trying to distribute to external testers

**Comment by madhurig** [comment] 2017-06-29 18:34
@JKennedy24 : Looks like a pilot bug that they fixed: https://github.com/fastlane/fastlane/issues/8964. Can you check what version of fastlane is on your deployment machine? The task also has "Advanced" options to update the fastlane tools version or pin to a specific version. 

Thanks,
Madhuri

**Comment by JKennedy24** [comment] 2017-06-30 08:25
@madhurig  how would I find out the fastlane versioned installed on my deployment machine?

**Comment by madhurig** [comment] 2017-06-30 17:18
@JKennedy24: You can run "fastlane -v" to get the version number on the deployment machine. If you don't have access to the machine and are using a cloud solution, you can run the same in a shell script and include it in your build. The output will show up in the log.

**Comment by JKennedy24** [comment] 2017-07-03 07:42
@madhurig I have access to my deployment machine. Running fastlane returns `not recognised`. I'm guessing its not on the path and is located somewhere as part of the vsts agent?

**Comment by madhurig** [comment] 2017-07-05 01:29
@JKennedy24 : Can you check the version of deliver on your deployment machine by running "deliver -v"? Please attach a debug log from your build.

Thanks,
Madhuri

**Comment by JKennedy24** [comment] 2017-07-05 07:32
@madhurig I logged onto the deployment machine and ran deliver -v but got the same `deliver is not recognised as an internal or external command` I'm guessing that's not on the path either? Is there a specific directory I should be running this command in?

**Comment by madhurig** [comment] 2017-07-13 09:42
@JKennedy24 : try "gem list fastlane" and "gem list fastlane deliver".  To update manually on the deployment machine run "gem update fastlane".

**Comment by JKennedy24** [comment] 2017-07-13 09:55
@madhurig Thanks for the reply. Have logged onto the deployment machine and ran `gem list fastlane` but again get `gem is not recognised as an internal or external command`

My deployment machine is a simple Windows 10 machine with VS2017 and Build agent running. All these commands sound like third party programs that are probably not installed or not on the path.

Should I be running them in a specific location? currently I am just running them in C:

**Comment by madhurig** [comment] 2017-07-13 11:33
@JKennedy24 : Publishing to the AppStore is only supported on macOS, we check for it in the tasks as well. Please verify if you have another machine in your agent queue.

**Comment by JKennedy24** [comment] 2017-07-13 11:40
I'm so sorry I just realised I've been running the commands on the wrong build machine! haha.

I have now ran these commands on my OSX MacBook-Pro

```
MacBook-Pro:~ user$ gem list fastlane

*** LOCAL GEMS ***


MacBook-Pro:~ user$ gem list fastlane deliver

*** LOCAL GEMS ***


MacBook-Pro:~ user$ fastlane -v
-bash: fastlane: command not found
MacBook-Pro:~ user$ gem update fastlane
Updating installed gems
Nothing to update
```

**Comment by madhurig** [comment] 2017-07-14 04:23
When I run "gem list fastlane", I get some version info on the console:

commander-fastlane (4.4.5)
fastlane (2.46.1, 2.44.0, 1.100.0)
fastlane_core (0.50.2)

Don't you see anything like that?

**Comment by JKennedy24** [comment] 2017-07-25 08:10
@madhurig Sorry for the delay in replying.

Running "gem list fastlane" returns a blank list. so I ran "gem list" and it returned this:

```
MacBook-Pro:~ me$ gem list

*** LOCAL GEMS ***

bigdecimal (1.2.0)
CFPropertyList (2.2.8)
io-console (0.4.2)
json (1.7.7)
libxml-ruby (2.6.0)
minitest (4.3.2)
nokogiri (1.5.6)
psych (2.0.0)
rake (0.9.6)
rdoc (4.0.0)
sqlite3 (1.3.7)
test-unit (2.0.0.0)
```

Very strange but looks like fastlane isnt installed?

**Comment by JKennedy24** [comment] 2017-08-11 15:20
Still getting the same erro:

> You must specify at least one group using the :groups option to distribute externally
> 2017-06-29T16:30:46.0587080Z ##[error]Error: fastlane failed with return code: 1

**Comment by JKennedy24** [comment] 2017-09-11 08:56
I don't think this is an issue with the `Fastlane` version.

From [this issue ](https://github.com/fastlane/fastlane/issues/8964) it says you must supply a group like so:

> groups: ["MyExternalGroupNameAsSpecifiedIniTunesConnect"]

Nowhere in the[ file ](https://github.com/Microsoft/app-store-vsts-extension/blob/master/Tasks/app-store-release/app-store-release.ts) can I see where the group is being supplied.

I think this is the true error and this feature of "Release to a team of testers" will never work without it

**Comment by madhurig** [comment] 2017-09-14 20:52
@JKennedy24 : Sorry for the delay. I am coming to the same conclusion that this new "group" field is now required for the feature to be usable. We will review and see if we can populate this by default. We have also been thinking of making it possible for customers to pass any additional arguments to fastlane in the task, that seems like a good idea here too. 

Thanks,
Madhuri

**Comment by JKennedy24** [comment] 2017-09-15 07:34
Thanks @madhurig for getting back to me and confirming my suspicions. I will follow this thread for further updates

**Comment by grubstarstar** [comment] 2017-09-26 11:04
I would also like to know when this is resolved as we're running into the same issue regarding :group not being specified. Thanks!

**Comment by madhurig** [comment] 2017-11-06 17:20
Fixed with latest release 1.126.0, let us know if you still see issues.

**Closed by madhurig** 2017-11-06 17:20 UTC

**Comment by JKennedy24** [comment] 2018-01-25 12:45
@madhurig I just tried to run our first test of distributing to external users but got an error:

2018-01-25T12:29:13.8815210Z [12:29:13]: Uploaded app 2.36 - 2.36.0, but received build 2.35 - 2.35.0. If you want to wait for uploaded build to be finished processing, use the `wait_for_uploaded_build` option
2018-01-25T12:29:17.3154290Z [12:29:17]: Successfully set the changelog for build
2018-01-25T12:29:17.3164460Z [12:29:17]: Distributing new build to testers: 2.35 - 2.35.0
2018-01-25T12:29:18.7536270Z 
2018-01-25T12:29:18.7547600Z Looking for related GitHub issues on fastlane/fastlane...
2018-01-25T12:29:18.7551870Z 
2018-01-25T12:29:19.3449030Z ➡️  Waiting for iTunes Connect to finish processing the new build 
2018-01-25T12:29:19.3460800Z     https://github.com/fastlane/fastlane/issues/9664 [closed] 16 💬
2018-01-25T12:29:19.3470690Z     29 Nov 2017
2018-01-25T12:29:19.3474870Z 
2018-01-25T12:29:19.3484860Z 🔗  You can ⌘ + double-click on links to open them directly in your browser.
2018-01-25T12:29:19.3497510Z /Users/chrisjohn/.gem-cache/gems/fastlane-2.78.0/spaceship/lib/spaceship/test_flight/client.rb:290:in `handle_response': [!] {"code"=>"ITC.response.error.INVALID_REQUEST", "description"=>"Failed to submit build for review."} (Spaceship::UnexpectedResponse)
2018-01-25T12:29:19.3510360Z 	from /Users/chrisjohn/.gem-cache/gems/fastlane-2.78.0/spaceship/lib/spaceship/test_flight/client.rb:72:in `post_for_testflight_review'
2018-01-25T12:29:19.3522620Z 	from /Users/chrisjohn/.gem-cache/gems/fastlane-2.78.0/spaceship/lib/spaceship/test_flight/build.rb:204:in `submit_for_testflight_review!'
2018-01-25T12:29:19.3534720Z 	from /Users/chrisjohn/.gem-cache/gems/fastlane-2.78.0/pilot/lib/pilot/build_manager.rb:149:in `distribute_build'
2018-01-25T12:29:19.3546740Z 	from /Users/chrisjohn/.gem-cache/gems/fastlane-2.78.0/pilot/lib/pilot/build_manager.rb:88:in `distribute'
2018-01-25T12:29:19.3558600Z 	from /Users/chrisjohn/.gem-cache/gems/fastlane-2.78.0/pilot/lib/pilot/build_manager.rb:52:in `upload'
2018-01-25T12:29:19.3570600Z 	from /Users/chrisjohn/.gem-cache/gems/fastlane-2.78.0/pilot/lib/pilot/commands_generator.rb:66:in `block (2 levels) in run'
2018-01-25T12:29:19.3582610Z 	from /Users/chrisjohn/.gem-cache/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
2018-01-25T12:29:19.3594470Z 	from /Users/chrisjohn/.gem-cache/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
2018-01-25T12:29:19.3606470Z 	from /Users/chrisjohn/.gem-cache/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
2018-01-25T12:29:19.3618500Z 	from /Users/chrisjohn/.gem-cache/gems/fastlane-2.78.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
2018-01-25T12:29:19.3630790Z 	from /Users/chrisjohn/.gem-cache/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
2018-01-25T12:29:19.3642680Z 	from /Users/chrisjohn/.gem-cache/gems/fastlane-2.78.0/pilot/lib/pilot/commands_generator.rb:166:in `run'
2018-01-25T12:29:19.3654580Z 	from /Users/chrisjohn/.gem-cache/gems/fastlane-2.78.0/pilot/lib/pilot/commands_generator.rb:18:in `start'
2018-01-25T12:29:19.3666510Z 	from /Users/chrisjohn/.gem-cache/gems/fastlane-2.78.0/fastlane/lib/fastlane/cli_tools_distributor.rb:90:in `take_off'
2018-01-25T12:29:19.3678430Z 	from /Users/chrisjohn/.gem-cache/gems/fastlane-2.78.0/bin/fastlane:20:in `<top (required)>'
2018-01-25T12:29:19.3689970Z 	from /Users/chrisjohn/.gem-cache/bin/fastlane:23:in `load'
2018-01-25T12:29:19.3701390Z 	from /Users/chrisjohn/.gem-cache/bin/fastlane:23:in `<main>'
2018-01-25T12:29:19.3712890Z 	from /Users/chrisjohn/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
2018-01-25T12:29:19.3724570Z 	from /Users/chrisjohn/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'

Interrestingly eventhough it failed the task the upload continued and it uploaded successfully to Itunes Connect but did not distribute to test users

**Comment by madhurig** [comment] 2018-01-26 19:41
@JKennedy24 : This seems to be something different unrelated to not specifying group. I only saw one fastlane issue on it reported by one customer but it was closed as no repro. Can you send me the full fastlane command line run by this release?

**Comment by JKennedy24** [comment] 2018-01-29 08:47
@madhurig heres the command my release is running:

`fastlane pilot upload -u ******** -i /Users/myuser/myagent/_work/r1/a/Daily Build - Xamarin.iOS/drop/MyAppiOS.ipa --changelog Test application -a com.mycompany.myapp --distribute_external true --groups myapp Testers`

**Comment by madhurig** [comment] 2018-03-02 21:29
@JKennedy24 : are you still seeing an issue here? I am able to distribute to my testers group without errors.
