### ISSUE TITLE
Invalid support URL in task

### ISSUE THREAD

**Issue by TsplayerT** [microsoft/app-store-vsts-extension#293] opened 2022-11-05 14:15 UTC
I have a Xamarin.iOS application that I want to automate the release of new versions in the store. I use `Azure DevOps Pipelines` with the `macos-12` agent ([_2.211.1_](https://github.com/actions/runner-images/releases/tag/macOS-12%2F20221027.1)) with this task ([_1.207.0_](https://github.com/microsoft/app-store-vsts-extension/tree/v1.207.0)):

```
- task: AppStoreRelease@1
  displayName: 'Distribute on AppStore'
  inputs:
    appType: 'iOS'
    ipaPath: '**/*.ipa'
    authType: 'ApiKey'
    teamId: '$(team_id)'
    apiKeyId: '$(api_key_id)'
    apiKeyIssuerId: '$(api_key_issuer_id)'
    apiToken: '$(api_token)'
    releaseTrack: 'Production'
    appIdentifier: 'br.com.company.app'
    installFastlane: false
    shouldAutoRelease: true
    shouldSubmitForReview: true
    shouldSkipWaitingForProcessing: true
    uploadMetadata: true
    metadataPath: $(System.DefaultWorkingDirectory)/Source/Mobile/Resource/Metadata
    fastlaneArguments: '--submission_information "{\"add_id_info_uses_idfa\": false}" --description --verbose'
```

- The problem is that when the **support_url.txt** file exists in the **default** metadata folder, the error occurs:
`An attribute value is invalid. - The Support URL you entered is invalid. Check the URL and try again`

- Without this file, the error I believe to be expected occurs:
`The provided entity is missing a required attribute - You must provide a value for the attribute 'supportUrl' with this request`

## More info

<details>
<summary>This is the run log</summary>

```
2022-11-05T09:06:44.4298620Z ##[section]Starting: Distribute on AppStore
2022-11-05T09:06:44.4316380Z ==============================================================================
2022-11-05T09:06:44.4316890Z Task         : Apple App Store Release
2022-11-05T09:06:44.4317280Z Description  : Release an app to TestFlight or the Apple App Store
2022-11-05T09:06:44.4317600Z Version      : 1.207.0
2022-11-05T09:06:44.4318080Z Author       : Microsoft Corporation
2022-11-05T09:06:44.4318540Z Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store)
2022-11-05T09:06:44.4319110Z ==============================================================================
2022-11-05T09:06:45.3555050Z Precheck will not check In-app purchases because Fastlane doesn't support it with the App Store Connect API Key.
2022-11-05T09:06:45.3591020Z [command]/usr/local/lib/ruby/gems/3.0.0/bin/fastlane deliver --force --precheck_include_in_app_purchases false --api_key_path /Users/runner/work/_temp/api_key.json -a br.com.company.app -i /Users/runner/work/1/s/Source/Mobile.iOS/bin/iPhone/Release/Mobile.iOS.ipa -j ios -m /Users/runner/work/1/s/Source/Mobile/Recurso/Metadata --skip_screenshots true -k 88SAC2QTFA --submit_for_review true --automatic_release true --submission_information {"add_id_info_uses_idfa": false} --verbose
2022-11-05T09:06:47.4885730Z [09:06:47]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
2022-11-05T09:06:50.3493400Z INFO [2022-11-05 09:06:50.34]: Sending anonymous analytics information
2022-11-05T09:06:50.3594530Z INFO [2022-11-05 09:06:50.34]: Learn more at https://docs.fastlane.tools/#metrics
2022-11-05T09:06:50.3702710Z INFO [2022-11-05 09:06:50.34]: No personal or sensitive data is sent.
2022-11-05T09:06:50.3805370Z INFO [2022-11-05 09:06:50.34]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
2022-11-05T09:06:50.3953920Z INFO [2022-11-05 09:06:50.39]: Creating authorization token for App Store Connect API
2022-11-05T09:06:51.6571060Z 
2022-11-05T09:06:51.6616040Z +----------------------------------------------+--------------------------------------------------------------------------------------+
2022-11-05T09:06:51.6617520Z |                                                       deliver 2.210.1 Summary                                                       |
2022-11-05T09:06:51.6618880Z +----------------------------------------------+--------------------------------------------------------------------------------------+
2022-11-05T09:06:51.6619970Z | force                                        | true                                                                                 |
2022-11-05T09:06:51.6622120Z | precheck_include_in_app_purchases            | false                                                                                |
2022-11-05T09:06:51.6623140Z | api_key_path                                 | /Users/runner/work/_temp/api_key.json                                      |
2022-11-05T09:06:51.6624300Z | app_identifier                               | br.com.company.app                                                        |
2022-11-05T09:06:51.6625320Z | ipa                                          | /Users/runner/work/1/s/Source/Mobile.iOS/bin/iPhone/Release/Mobile.iOS.ipa |
2022-11-05T09:06:51.6626260Z | platform                                     | ios                                                                                  |
2022-11-05T09:06:51.6627180Z | metadata_path                                | /Users/runner/work/1/s/Source/Mobile/Recurso/Metadata                           |
2022-11-05T09:06:51.6628120Z | skip_screenshots                             | true                                                                                 |
2022-11-05T09:06:51.6628980Z | team_id                                      | 88SAC2QTFA                                                                           |
2022-11-05T09:06:51.6630660Z | submit_for_review                            | true                                                                                 |
2022-11-05T09:06:51.6631550Z | automatic_release                            | true                                                                                 |
2022-11-05T09:06:51.6632460Z | submission_information.add_id_info_uses_idfa | false                                                                                |
2022-11-05T09:06:51.6633380Z | screenshots_path                             | ./screenshots                                                                        |
2022-11-05T09:06:51.6634270Z | app_version                                  | 20221105.7                                                                           |
2022-11-05T09:06:51.6635130Z | edit_live                                    | false                                                                                |
2022-11-05T09:06:51.6635980Z | use_live_version                             | false                                                                                |
2022-11-05T09:06:51.6636850Z | skip_binary_upload                           | false                                                                                |
2022-11-05T09:06:51.6637700Z | skip_metadata                                | false                                                                                |
2022-11-05T09:06:51.6638570Z | skip_app_version_update                      | false                                                                                |
2022-11-05T09:06:51.6639840Z | overwrite_screenshots                        | false                                                                                |
2022-11-05T09:06:51.6640710Z | sync_screenshots                             | false                                                                                |
2022-11-05T09:06:51.6641560Z | verify_only                                  | false                                                                                |
2022-11-05T09:06:51.6642420Z | reject_if_possible                           | false                                                                                |
2022-11-05T09:06:51.6643270Z | phased_release                               | false                                                                                |
2022-11-05T09:06:51.6644120Z | reset_ratings                                | false                                                                                |
2022-11-05T09:06:51.6645000Z | run_precheck_before_submit                   | true                                                                                 |
2022-11-05T09:06:51.6645890Z | precheck_default_rule_level                  | warn                                                                                 |
2022-11-05T09:06:51.6646900Z | ignore_language_directory_validation         | false                                                                                |
2022-11-05T09:06:51.6648200Z +----------------------------------------------+--------------------------------------------------------------------------------------+
2022-11-05T09:06:51.6648940Z 
2022-11-05T09:06:51.6650020Z INFO [2022-11-05 09:06:51.66]: Making sure the latest version on App Store Connect matches '20221105.7'...
2022-11-05T09:06:52.1301560Z INFO [2022-11-05 09:06:52.11]: Successfully set the version to '20221105.7'
2022-11-05T09:06:52.1354600Z INFO [2022-11-05 09:06:52.12]: Loading '/Users/runner/work/1/s/Source/Mobile/Recurso/Metadata/default/description.txt'...
2022-11-05T09:06:52.1362420Z INFO [2022-11-05 09:06:52.12]: Loading '/Users/runner/work/1/s/Source/Mobile/Recurso/Metadata/default/keywords.txt'...
2022-11-05T09:06:52.1367860Z INFO [2022-11-05 09:06:52.12]: Loading '/Users/runner/work/1/s/Source/Mobile/Recurso/Metadata/default/release_notes.txt'...
2022-11-05T09:06:52.1470030Z INFO [2022-11-05 09:06:52.12]: Loading '/Users/runner/work/1/s/Source/Mobile/Recurso/Metadata/default/support_url.txt'...
2022-11-05T09:06:52.1573310Z INFO [2022-11-05 09:06:52.12]: Loading '/Users/runner/work/1/s/Source/Mobile/Recurso/Metadata/default/promotional_text.txt'...
2022-11-05T09:06:52.1675740Z INFO [2022-11-05 09:06:52.12]: Loading '/Users/runner/work/1/s/Source/Mobile/Recurso/Metadata/en-US/description.txt'...
2022-11-05T09:06:52.1778140Z INFO [2022-11-05 09:06:52.12]: Loading '/Users/runner/work/1/s/Source/Mobile/Recurso/Metadata/en-US/keywords.txt'...
2022-11-05T09:06:52.1880340Z INFO [2022-11-05 09:06:52.12]: Loading '/Users/runner/work/1/s/Source/Mobile/Recurso/Metadata/en-US/release_notes.txt'...
2022-11-05T09:06:52.1982810Z INFO [2022-11-05 09:06:52.12]: Loading '/Users/runner/work/1/s/Source/Mobile/Recurso/Metadata/en-US/support_url.txt'...
2022-11-05T09:06:52.2085220Z INFO [2022-11-05 09:06:52.12]: Loading '/Users/runner/work/1/s/Source/Mobile/Recurso/Metadata/en-US/promotional_text.txt'...
2022-11-05T09:06:52.2187620Z INFO [2022-11-05 09:06:52.12]: Loading '/Users/runner/work/1/s/Source/Mobile/Recurso/Metadata/es-MX/description.txt'...
2022-11-05T09:06:52.2290130Z INFO [2022-11-05 09:06:52.12]: Loading '/Users/runner/work/1/s/Source/Mobile/Recurso/Metadata/es-MX/keywords.txt'...
2022-11-05T09:06:52.2317150Z INFO [2022-11-05 09:06:52.12]: Loading '/Users/runner/work/1/s/Source/Mobile/Recurso/Metadata/es-MX/release_notes.txt'...
2022-11-05T09:06:52.2342390Z INFO [2022-11-05 09:06:52.12]: Loading '/Users/runner/work/1/s/Source/Mobile/Recurso/Metadata/es-MX/support_url.txt'...
2022-11-05T09:06:52.2369550Z INFO [2022-11-05 09:06:52.12]: Loading '/Users/runner/work/1/s/Source/Mobile/Recurso/Metadata/es-MX/promotional_text.txt'...
2022-11-05T09:06:52.2394690Z INFO [2022-11-05 09:06:52.12]: Loading '/Users/runner/work/1/s/Source/Mobile/Recurso/Metadata/pt-BR/description.txt'...
2022-11-05T09:06:52.2416010Z INFO [2022-11-05 09:06:52.12]: Loading '/Users/runner/work/1/s/Source/Mobile/Recurso/Metadata/pt-BR/keywords.txt'...
2022-11-05T09:06:52.2421630Z INFO [2022-11-05 09:06:52.12]: Loading '/Users/runner/work/1/s/Source/Mobile/Recurso/Metadata/pt-BR/release_notes.txt'...
2022-11-05T09:06:52.2444610Z INFO [2022-11-05 09:06:52.12]: Loading '/Users/runner/work/1/s/Source/Mobile/Recurso/Metadata/pt-BR/support_url.txt'...
2022-11-05T09:06:52.2445960Z INFO [2022-11-05 09:06:52.12]: Loading '/Users/runner/work/1/s/Source/Mobile/Recurso/Metadata/pt-BR/promotional_text.txt'...
2022-11-05T09:06:52.2470640Z INFO [2022-11-05 09:06:52.12]: Detected languages: ["default", "en-US", "es-MX", "pt-BR"]
2022-11-05T09:06:57.1248180Z WARN [2022-11-05 09:06:57.12]: Will begin uploading metadata for '20221105.7' on App Store Connect
2022-11-05T09:06:57.1249950Z INFO [2022-11-05 09:06:57.12]: Uploading metadata to App Store Connect for version
2022-11-05T09:07:00.2844170Z INFO [2022-11-05 09:07:00.28]: Uploading metadata to App Store Connect for localized version 'en-US'
2022-11-05T09:07:00.3952510Z INFO [2022-11-05 09:07:00.28]: Uploading metadata to App Store Connect for localized version 'pt-BR'
2022-11-05T09:07:00.3990190Z INFO [2022-11-05 09:07:00.28]: Uploading metadata to App Store Connect for localized version 'es-MX'
2022-11-05T09:07:00.5784600Z #<Thread:0x00007fd63581f318 /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/fastlane_core/lib/fastlane_core/queue_worker.rb:37 run> terminated with exception (report_on_exception is true):
2022-11-05T09:07:00.5792160Z /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/api_client.rb:204:in `handle_response': An attribute value is invalid. - The Support URL you entered is invalid. Check the URL and try again. - /data/attributes/supportUrl (Spaceship::UnexpectedResponse)
2022-11-05T09:07:00.5795380Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/api_client.rb:135:in `patch'
2022-11-05T09:07:00.5803030Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:815:in `patch_app_store_version_localization'
2022-11-05T09:07:00.5824210Z 	from /usr/local/Cellar/ruby@3.0/3.0.4_1/lib/ruby/3.0.0/forwardable.rb:238:in `patch_app_store_version_localization'
2022-11-05T09:07:00.5825790Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/models/app_store_version_localization.rb:57:in `update'
2022-11-05T09:07:00.5835920Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/deliver/lib/deliver/upload_metadata.rb:207:in `block in upload'
2022-11-05T09:07:00.5837800Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/fastlane_core/lib/fastlane_core/queue_worker.rb:40:in `block (2 levels) in start'
2022-11-05T09:07:00.5841580Z #<Thread:0x00007fd63581f110 /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/fastlane_core/lib/fastlane_core/queue_worker.rb:37 run> terminated with exception (report_on_exception is true):
2022-11-05T09:07:00.5849130Z /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/api_client.rb:204:in `handle_response': An attribute value is invalid. - The Support URL you entered is invalid. Check the URL and try again. - /data/attributes/supportUrl (Spaceship::UnexpectedResponse)
2022-11-05T09:07:00.5852490Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/api_client.rb:135:in `patch'
2022-11-05T09:07:00.5854080Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:815:in `patch_app_store_version_localization'
2022-11-05T09:07:00.5867330Z 	from /usr/local/Cellar/ruby@3.0/3.0.4_1/lib/ruby/3.0.0/forwardable.rb:238:in `patch_app_store_version_localization'
2022-11-05T09:07:00.5869230Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/models/app_store_version_localization.rb:57:in `update'
2022-11-05T09:07:00.5881220Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/deliver/lib/deliver/upload_metadata.rb:207:in `block in upload'
2022-11-05T09:07:00.5883050Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/fastlane_core/lib/fastlane_core/queue_worker.rb:40:in `block (2 levels) in start'
2022-11-05T09:07:00.5893630Z 
2022-11-05T09:07:00.5907030Z Looking for related GitHub issues on fastlane/fastlane...
2022-11-05T09:07:00.5908660Z Search query: An attribute value is invalid. - The Support URL you entered is invalid. Check the URL and try again. - /data/attributes/supportUrl
2022-11-05T09:07:00.5909580Z 
2022-11-05T09:07:00.5911230Z URL: https://api.github.com/search/issues?q=An%20attribute%20value%20is%20invalid.%20-%20The%20Support%20URL%20you%20entered%20is%20invalid.%20Check%20the%20URL%20and%20try%20again.%20-%20%2Fdata%2Fattributes%2FsupportUrl+repo:fastlane/fastlane
2022-11-05T09:07:00.6038350Z #<Thread:0x00007fd63581f200 /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/fastlane_core/lib/fastlane_core/queue_worker.rb:37 run> terminated with exception (report_on_exception is true):
2022-11-05T09:07:00.6040880Z /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/api_client.rb:204:in `handle_response': An attribute value is invalid. - The Support URL you entered is invalid. Check the URL and try again. - /data/attributes/supportUrl (Spaceship::UnexpectedResponse)
2022-11-05T09:07:00.6042490Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/api_client.rb:135:in `patch'
2022-11-05T09:07:00.6044160Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:815:in `patch_app_store_version_localization'
2022-11-05T09:07:00.6045740Z 	from /usr/local/Cellar/ruby@3.0/3.0.4_1/lib/ruby/3.0.0/forwardable.rb:238:in `patch_app_store_version_localization'
2022-11-05T09:07:00.6047340Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/models/app_store_version_localization.rb:57:in `update'
2022-11-05T09:07:00.6049500Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/deliver/lib/deliver/upload_metadata.rb:207:in `block in upload'
2022-11-05T09:07:00.6054700Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/fastlane_core/lib/fastlane_core/queue_worker.rb:40:in `block (2 levels) in start'
2022-11-05T09:07:00.8136090Z Found no similar issues. To create a new issue, please visit:
2022-11-05T09:07:00.8140100Z https://github.com/fastlane/fastlane/issues/new
2022-11-05T09:07:00.8141080Z Run `fastlane env` to append the fastlane environment to your issue
2022-11-05T09:07:00.8143160Z /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/api_client.rb:204:in `handle_response': [!] An attribute value is invalid. - The Support URL you entered is invalid. Check the URL and try again. - /data/attributes/supportUrl (Spaceship::UnexpectedResponse)
2022-11-05T09:07:00.8145130Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/api_client.rb:135:in `patch'
2022-11-05T09:07:00.8146710Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:815:in `patch_app_store_version_localization'
2022-11-05T09:07:00.8148210Z 	from /usr/local/Cellar/ruby@3.0/3.0.4_1/lib/ruby/3.0.0/forwardable.rb:238:in `patch_app_store_version_localization'
2022-11-05T09:07:00.8149710Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/models/app_store_version_localization.rb:57:in `update'
2022-11-05T09:07:00.8151190Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/deliver/lib/deliver/upload_metadata.rb:207:in `block in upload'
2022-11-05T09:07:00.8153400Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/fastlane_core/lib/fastlane_core/queue_worker.rb:40:in `block (2 levels) in start'
2022-11-05T09:07:00.8155340Z /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/api_client.rb:204:in `handle_response': An attribute value is invalid. - The Support URL you entered is invalid. Check the URL and try again. - /data/attributes/supportUrl (Spaceship::UnexpectedResponse)
2022-11-05T09:07:00.8157130Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/api_client.rb:135:in `patch'
2022-11-05T09:07:00.8158650Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:815:in `patch_app_store_version_localization'
2022-11-05T09:07:00.8160130Z 	from /usr/local/Cellar/ruby@3.0/3.0.4_1/lib/ruby/3.0.0/forwardable.rb:238:in `patch_app_store_version_localization'
2022-11-05T09:07:00.8161670Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/models/app_store_version_localization.rb:57:in `update'
2022-11-05T09:07:00.8163160Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/deliver/lib/deliver/upload_metadata.rb:207:in `block in upload'
2022-11-05T09:07:00.8164640Z 	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.210.1/fastlane_core/lib/fastlane_core/queue_worker.rb:40:in `block (2 levels) in start'
2022-11-05T09:07:00.8395250Z ##[error]Error: The process '/usr/local/lib/ruby/gems/3.0.0/bin/fastlane' failed with exit code 1
2022-11-05T09:07:00.8414340Z ##[section]Finishing: Distribute on AppStore
```
</details>

<details>
<summary>sample content of file <b>support_url.txt</b></summary>

`https://example.com.br/`
</details>

<details>
<summary>file tree</summary>

![error-appstorerelease-direc](https://user-images.githubusercontent.com/6465230/200124238-96c5c067-3975-4fea-86bb-9a89a2a369dc.png)
</details>

##
Can you help me please? 😞

**Comment by DmitriiBobreshev** [comment] 2022-11-07 14:44
Hi @TsplayerT thank you for the question, AppStoreRelease Task using [fastline ](https://docs.fastlane.tools/) for creating releases, so the schema is the same, and your file tree [looks correct](http://docs.fastlane.tools/actions/deliver/#parameters), but support URL now required option according to [AppStore policy](https://help.apple.com/app-store-connect/#/devf29afbb74) at least for production releases, and must lead to actual contact information, so the error you get is not from task or fastline, but from apple. 
As I see in fastline [examples](https://github.com/fastlane/examples/blob/master/Wikipedia/metadata/en-US/support_url.txt) URL should be valid and available. So in your case, it may be that URL is not available

**Comment by TsplayerT** [comment] 2022-11-07 16:36
@DmitriiBobreshev  I understand how it works, it really looks like an error returned by the Apple system API but I keep getting an error using a website URL that is live, using the `https` protocol, with the certificates and domain updated and correct 😢

##
Can you tell me where you have an **example repository** using this Azure DevOps Pipelines task making continuous delivery of a `Xamarin.iOS` application to the Apple store?

**Comment by DmitriiBobreshev** [comment] 2022-11-08 10:42
Hi @TsplayerT, unfortunately, we don't have an application which we are publishing to AppStore production, so we don't have an example with `releaseTrack: 'Production'` and metadata configuration, the only example that we have is how to deploy [Xcode article](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/xcode?view=azure-devops#release), but this case for  `releaseTrack: 'TestFlight'`

**Comment by TsplayerT** [comment] 2022-11-08 18:02
@max-zaytsev  yes, I can set the URL manually by `AppStoreConnect`

**Comment by max-zaytsev** [comment] 2022-11-09 21:31
@TsplayerT your example "https://example.com.br/" works fine for me. 
The issue is reproduced when there is a broken link like "htpp:/example" in folders with localization (en-US, es-MX, etc.)
Please check that you have the same link (https://example.com.br/ ) in all support_url.txt files

**Comment by max-zaytsev** [comment] 2022-11-15 09:17
@TsplayerT did you manage to resolve your issue?

**Comment by max-zaytsev** [comment] 2022-11-18 10:05
@TsplayerT Closing this as it doesn't look like a problem with the task.

**Closed by max-zaytsev** 2022-11-18 10:05 UTC
Labels: help wanted, Area: AppStore

**Comment by TsplayerT** [comment] 2022-11-21 12:04
@max-zaytsev  I managed to solve the problem by leaving only 1 file `support_url.txt` and located in the `default` folder. 

![Screenshot_3](https://user-images.githubusercontent.com/6465230/203048617-13b9a418-058b-490b-b0c2-f47812d939a7.png)
