### ISSUE TITLE
Could not set team ID to '***', only found the following available teams

### ISSUE THREAD

**Issue by krishnagopinath** [microsoft/app-store-vsts-extension#112] opened 2019-03-04 22:03 UTC
We've been seeing the following error when trying to build today: 

```
[!] The request could not be completed because:
    Could not set team ID to '*******', only found the following available teams:

- 12612312 (Fun LLC)
- 287634632 (Range LLC)
```

Here are the complete logs, if you're interested: 

```
==============================================================================
Task         : Apple App Store Release
Description  : Release an app to TestFlight or the Apple App Store
Version      : 1.147.0
Author       : Microsoft Corporation
Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store)
==============================================================================
[command]/Users/****/.rvm/rubies/ruby-2.3.0/bin/gem install fastlane
Successfully installed fastlane-2.117.1
Parsing documentation for fastlane-2.117.1
Done installing documentation for fastlane after 15 seconds
1 gem installed
[command]/Users/**/.rvm/rubies/ruby-2.3.0/bin/gem update fastlane -i /Users/****/.gem-cache
Updating installed gems
Nothing to update
[command]fastlane pilot upload -u dev@****.com -i /Users/**/myagent/_work/24/s/cordova/platforms/ios/build/device/**.ipa -q ****** -r FUN LLC -a com.****.app --skip_waiting_for_build_processing true
[15:56:36]: ‌Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile‌
[15:56:38]: Login to App Store Connect (dev@****.com)
Available session is not valid any more. Continuing with normal login.

Looking for related GitHub issues on fastlane/fastlane...

➡️  Execution fails on fastlane-0.1.14
    https://github.com/fastlane/fastlane/issues/79 [closed] 5 💬
    22 Sep 2016

➡️  Documentation - ipa vs. ipa (shenzhen)?
    https://github.com/fastlane/fastlane/issues/72 [closed] 2 💬
    22 Sep 2016

➡️  Extension Support
    https://github.com/fastlane/fastlane/issues/76 [closed] 6 💬
    11 Dec 2016

and 14279 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Could%20not%20set%20team%20ID%20to%20%27X8T3TCZ8WD%27%2C%20only%20found%20the%20following%20available%20teams%3A%0A%0A-%20118025167%20%28Field%20Nimble%20LLC%29%0A-%20914103%20%28****%2C%20LLC%29%0A&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] The request could not be completed because:
    Could not set team ID to '*******', only found the following available teams:

- 12612312 (Fun LLC)
- 287634632 (Range LLC)
##[error]Error: fastlane failed with return code: 1
##[section]Finishing: Publish to the App Store TestFlight track
```

**Comment by alexvy86** [comment] 2020-02-19 19:08
I had the same issue today, I tried using our 10-character TeamID as seen in the Apple Developer Portal, and the logs gave me ids that don't match anything I can find there... Changing what I initialy used for the one from the logs fixed this error, but it shouldn't be necessary to obtain some internal id from a failed build log in order to get this to work...?
![image](https://user-images.githubusercontent.com/716334/74866376-68c0ae80-5318-11ea-98f8-794bc753bc31.png)
![image](https://user-images.githubusercontent.com/716334/74866570-b76e4880-5318-11ea-845a-6ec5ca57e7ae.png)

**Comment by anatolybolshakov** [comment] 2020-10-29 09:52
Hi @krishnagopinath @alexvy86 is it still actual for you? We can't reproduce this issue currently - using team id from the page you mentioned seems to work fine.

**Comment by alexvy86** [comment] 2020-10-29 19:05
I'm not working on the project that had this issue anymore so unfortunately I can't say :/ sorry!

**Comment by anatolybolshakov** [comment] 2020-11-10 11:29
@alexvy86 ok, thanks 👍 
@krishnagopinath I'm closing it at the moment - please feel free to reopen if it's still actual for you

**Closed by anatolybolshakov** 2020-11-10 11:29 UTC
Labels: Task: AppStoreRelease, bug

**Comment by rsg73626** [comment] 2021-01-05 14:50
Hi. I'm having this issue.

**Comment by mithunmqb** [comment] 2021-01-26 15:05
Ran into this issue today
