### ISSUE TITLE
Some passwords do not work when using AppStoreRelease

### ISSUE THREAD

**Issue by Tragetaschen** [microsoft/app-store-vsts-extension#148] opened 2020-04-16 13:58 UTC
I tried to setup an Apple ID specific for CI purposes today. Specifically one without 2FA to avoid all the issues around it.

The Apple ID's password was(!) `LA9_yCiO7_UJqXdmCGO*3(lx` and with this password, the task consistently failed even though manually using `Transporter` on a Mac with the new Apple ID worked flawlessly. I have changed the password since so it only consists of shell-safe characters (A-Z, a-z, 0-9), stored that in the service endpoint, reran the failed Job and that fixed the upload error.

Here's the log from a failed attempt:
```
2020-04-16T10:04:20.2348640Z Successfully installed fastlane-2.145.0
2020-04-16T10:04:20.2349980Z Parsing documentation for fastlane-2.145.0
2020-04-16T10:04:20.2350890Z Installing ri documentation for fastlane-2.145.0
2020-04-16T10:04:20.2351380Z Done installing documentation for fastlane after 19 seconds
2020-04-16T10:04:20.2351820Z 1 gem installed
2020-04-16T10:04:20.2619490Z [command]/usr/local/opt/ruby/bin/gem update fastlane -i /Users/runner/.gem-cache
2020-04-16T10:04:22.8854080Z Updating installed gems
2020-04-16T10:04:22.8854700Z Nothing to update
2020-04-16T10:04:22.9094820Z 
2020-04-16T10:04:22.9096380Z [command]fastlane pilot upload -u *** -i /Users/runner/runners/2.166.2/work/1/[redacted] --changelog [redacted]
2020-04-16T10:04:22.9096880Z 
2020-04-16T10:04:25.8199900Z [10:04:25]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
2020-04-16T10:04:29.9760260Z [10:04:29]: Sending anonymous analytics information
2020-04-16T10:04:29.9761020Z [10:04:29]: Learn more at https://docs.fastlane.tools/#metrics
2020-04-16T10:04:29.9761480Z [10:04:29]: No personal or sensitive data is sent.
2020-04-16T10:04:29.9761920Z [10:04:29]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
2020-04-16T10:04:29.9976220Z [10:04:29]: Login to App Store Connect (***)
2020-04-16T10:04:30.4475170Z Session loaded from environment variable is not valid. Continuing with normal login.
2020-04-16T10:04:32.0379220Z [10:04:32]: Login successful
2020-04-16T10:04:33.1595540Z [10:04:33]: Ready to upload new build to TestFlight (App: [redacted])...
2020-04-16T10:04:33.2874950Z [10:04:33]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
2020-04-16T10:04:33.2875630Z [10:04:33]: Going to upload updated app to App Store Connect
2020-04-16T10:04:33.2876900Z [10:04:33]: This might take a few minutes. Please don't interrupt the script.
2020-04-16T10:04:49.8809200Z [10:04:49]: [Transporter Error Output]: Your account information was entered incorrectly. (-20101)
2020-04-16T10:04:49.9721320Z [10:04:49]: Transporter transfer failed.
2020-04-16T10:04:49.9722340Z [10:04:49]: 
2020-04-16T10:04:49.9723790Z [10:04:49]: Your account information was entered incorrectly. (-20101)```

**Comment by anatolybolshakov** [comment] 2020-09-07 13:19
Hi @Tragetaschen is issue still actual for you?

**Comment by Tragetaschen** [comment] 2020-09-07 17:10
Dunno. I haven't tried changing the password back to something non-alphanumerical.

**Comment by anatolybolshakov** [comment] 2020-09-17 12:38
@Tragetaschen we can't reproduce this issue currently... Did you change only Apple ID password, without changing App specific password? It seems from logs that Login to App Store Connect was successful using appleid/password, but there was some error on upload step - for which app specific password is used

**Comment by Tragetaschen** [comment] 2020-09-17 17:32
I'm very certain that I only changed the Apple ID's password to fix the build, but I concur that the log seems to suggest differently.
I have a new employer since, so I cannot go back and check. There's a pretty good chance that we are using the Task in the future, though.

**Comment by anatolybolshakov** [comment] 2020-09-18 11:48
@Tragetaschen ok thanks! Since we are not able to reproduce it currently, I'm going to close it at the moment, but please feel free to reopen it if this issue appears again

**Closed by anatolybolshakov** 2020-09-18 11:48 UTC
Labels: Task: AppStoreRelease, bug
