### ISSUE TITLE
The "Binary Path" field is hidden for Test Flight release track

### ISSUE THREAD

**Issue by Max-Might** [microsoft/app-store-vsts-extension#191] opened 2020-11-05 22:50 UTC
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AppStoreRelease  

## Issue Description

Currently the "Binary Path" field is visible only if the "Track" field is "Production".
The issue is that the "Binary Path" is needed also for "Test Flight" releases so the field should always be visible.

A temporary workaround is to set the track to Production and set a Binary Path value and then save the release and change the Track field back to Test Flight and save again. This way the field is hidden again but the value is updated.

**Comment by alexander-smolyakov** [comment] 2020-11-06 12:02
Hi, @Max-Might! 
Thanks for opening the issue!

The [PR](https://github.com/microsoft/app-store-vsts-extension/pull/193) with the fix was merged and it will available with the next release of the extension. I'll let you know once the release with the fix is deployed.

**Comment by alexander-smolyakov** [comment] 2020-11-09 06:37
@Max-Might, fix was already released, I'm closing it at the moment - please feel free to reopen if the issue is still reproducible.

**Closed by alexander-smolyakov** 2020-11-09 06:37 UTC
Labels: Task: AppStoreRelease, awaiting deployment, bug
