### ISSUE TITLE
Apple App Store Release - Could not find option 'env' in the list of available options

### ISSUE THREAD

**Issue by jonsamwell** [microsoft/app-store-vsts-extension#152] opened 2020-05-18 05:27 UTC
We are getting the above error when trying to release to the app store, this task has worked fine in the passed - we haven't done a production release in the last 4 weeks so something has broken it since then.  It looks like our last successful release was with Fastlane version `fastlane-2.144.0`.

The task fails with the same error no matter the options selected in the `Apple App Store Release
`

The debug logs are below.  

Any help to fix this issue would be much appreciated!

```
2020-05-18T05:11:58.1549660Z ==============================================================================
2020-05-18T05:11:58.1550100Z Task         : Apple App Store Release
2020-05-18T05:11:58.1550460Z Description  : Release an app to TestFlight or the Apple App Store
2020-05-18T05:11:58.1550840Z Version      : 1.158.0
2020-05-18T05:11:58.1551150Z Author       : Microsoft Corporation
2020-05-18T05:11:58.1552510Z Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store)
2020-05-18T05:11:58.1553090Z ==============================================================================
2020-05-18T05:11:58.3069150Z ##[debug]agent.workFolder=/Users/runner/runners/2.168.2/work
2020-05-18T05:11:58.3094450Z ##[debug]loading inputs and endpoints
2020-05-18T05:11:58.3098410Z ##[debug]loading INPUT_AUTHTYPE
2020-05-18T05:11:58.3109730Z ##[debug]loading INPUT_SERVICEENDPOINT
2020-05-18T05:11:58.3113880Z ##[debug]loading INPUT_ISTWOFACTORAUTH
2020-05-18T05:11:58.3114430Z ##[debug]loading INPUT_APPIDENTIFIER
2020-05-18T05:11:58.3115980Z ##[debug]loading INPUT_APPTYPE
2020-05-18T05:11:58.3117200Z ##[debug]loading INPUT_IPAPATH
2020-05-18T05:11:58.3118840Z ##[debug]loading INPUT_RELEASETRACK
2020-05-18T05:11:58.3120310Z ##[debug]loading INPUT_SKIPBINARYUPLOAD
2020-05-18T05:11:58.3121640Z ##[debug]loading INPUT_UPLOADMETADATA
2020-05-18T05:11:58.3123150Z ##[debug]loading INPUT_METADATAPATH
2020-05-18T05:11:58.3124490Z ##[debug]loading INPUT_UPLOADSCREENSHOTS
2020-05-18T05:11:58.3127160Z ##[debug]loading INPUT_SCREENSHOTSPATH
2020-05-18T05:11:58.3137780Z ##[debug]loading INPUT_SHOULDSUBMITFORREVIEW
2020-05-18T05:11:58.3139340Z ##[debug]loading INPUT_SHOULDAUTORELEASE
2020-05-18T05:11:58.3140690Z ##[debug]loading INPUT_RELEASENOTES
2020-05-18T05:11:58.3142080Z ##[debug]loading INPUT_SHOULDSKIPWAITINGFORPROCESSING
2020-05-18T05:11:58.3143680Z ##[debug]loading INPUT_SHOULDSKIPSUBMISSION
2020-05-18T05:11:58.3146150Z ##[debug]loading INPUT_DISTRIBUTEDTOEXTERNALTESTERS
2020-05-18T05:11:58.3149300Z ##[debug]loading INPUT_TEAMID
2020-05-18T05:11:58.3152040Z ##[debug]loading INPUT_TEAMNAME
2020-05-18T05:11:58.3153700Z ##[debug]loading INPUT_INSTALLFASTLANE
2020-05-18T05:11:58.3154760Z ##[debug]loading INPUT_FASTLANETOOLSVERSION
2020-05-18T05:11:58.3156230Z ##[debug]loading INPUT_FASTLANEARGUMENTS
2020-05-18T05:11:58.3158290Z ##[debug]loading ENDPOINT_AUTH_HIDDEN-7d53-4cf4-8913-90cac59ad7bd
2020-05-18T05:11:58.3159770Z ##[debug]loading ENDPOINT_AUTH_SCHEME_HIDDEN-7d53-4cf4-8913-90cac59ad7bd
2020-05-18T05:11:58.3161080Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_HIDDEN-7d53-4cf4-8913-90cac59ad7bd_USERNAME
2020-05-18T05:11:58.3162470Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_HIDDEN-7d53-4cf4-8913-90cac59ad7bd_PASSWORD
2020-05-18T05:11:58.3164300Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_HIDDEN-7d53-4cf4-8913-90cac59ad7bd_FASTLANESESSION
2020-05-18T05:11:58.3165160Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2020-05-18T05:11:58.3166090Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2020-05-18T05:11:58.3167830Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2020-05-18T05:11:58.3171060Z ##[debug]loaded 31
2020-05-18T05:11:58.3197570Z ##[debug]check path : /Users/runner/runners/2.168.2/work/_tasks/AppStoreRelease_HIDDEN-da5e-11e5-83da-0943b1acc572/1.158.0/task.json
2020-05-18T05:11:58.3199080Z ##[debug]set resource file to: /Users/runner/runners/2.168.2/work/_tasks/AppStoreRelease_HIDDEN-da5e-11e5-83da-0943b1acc572/1.158.0/task.json
2020-05-18T05:11:58.3200030Z ##[debug]system.culture=en-US
2020-05-18T05:11:58.3222920Z ##[debug]authType=ServiceEndpoint
2020-05-18T05:11:58.3227500Z ##[debug]serviceEndpoint=HIDDEN-7d53-4cf4-8913-90cac59ad7bd
2020-05-18T05:11:58.3251940Z 0895f508-7d53-4cf4-8913-90cac59ad7bd exists true
2020-05-18T05:11:58.3252780Z ##[debug]0895f508-7d53-4cf4-8913-90cac59ad7bd exists true
2020-05-18T05:11:58.3253720Z ##[debug]ipaPath=/Users/runner/runners/2.168.2/work/r1/a/HIDDEN/HIDDEN/output/production/iphoneos/Release/Runner.ipa
2020-05-18T05:11:58.3254880Z ##[debug]skipBinaryUpload=false
2020-05-18T05:11:58.3260610Z ##[debug]uploadMetadata=false
2020-05-18T05:11:58.3262040Z ##[debug]metadataPath=/Users/runner/runners/2.168.2/work/r1/a/HIDDEN/HIDDEN/metadata/
2020-05-18T05:11:58.3262790Z ##[debug]uploadScreenshots=false
2020-05-18T05:11:58.3264600Z ##[debug]screenshotsPath=/Users/runner/runners/2.168.2/work/r1/a/HIDDEN/HIDDEN/metadata/screenshots/
2020-05-18T05:11:58.3265810Z ##[debug]releaseNotes=/Users/runner/runners/2.168.2/work/r1/a
2020-05-18T05:11:58.3267380Z ##[debug]releaseTrack=Production
2020-05-18T05:11:58.3268260Z ##[debug]shouldSkipWaitingForProcessing=false
2020-05-18T05:11:58.3269780Z ##[debug]shouldSubmitForReview=true
2020-05-18T05:11:58.3276140Z ##[debug]shouldAutoRelease=true
2020-05-18T05:11:58.3277320Z ##[debug]shouldSkipSubmission=false
2020-05-18T05:11:58.3278400Z ##[debug]teamId=HIDDEN
2020-05-18T05:11:58.3279430Z ##[debug]teamName=HIDDEN LTD
2020-05-18T05:11:58.3282070Z ##[debug]appType=iOS
2020-05-18T05:11:58.3282840Z ##[debug]installFastlane=true
2020-05-18T05:11:58.3283860Z ##[debug]fastlaneToolsVersion=LatestVersion
2020-05-18T05:11:58.3284350Z ##[debug]GEM_CACHE=undefined
2020-05-18T05:11:58.3287710Z ##[debug]gemCache=/Users/runner/.gem-cache
2020-05-18T05:11:58.3290030Z ##[debug]glob /Users/runner/runners/2.168.2/work/r1/a/HIDDEN/HIDDEN/output/production/iphoneos/Release/Runner.ipa
2020-05-18T05:11:58.3340680Z ##[debug]found 1 matches
2020-05-18T05:11:58.3341110Z ##[debug]matches:
2020-05-18T05:11:58.3341980Z ##[debug]/Users/runner/runners/2.168.2/work/r1/a/HIDDEN/HIDDEN/output/production/iphoneos/Release/Runner.ipa
2020-05-18T05:11:58.3342630Z ##[debug]Checking for ruby install...
2020-05-18T05:11:58.3353060Z ##[debug]check path : /usr/local/opt/ruby/bin/ruby
2020-05-18T05:11:58.3353610Z ##[debug]ruby=/usr/local/opt/ruby/bin/ruby
2020-05-18T05:11:58.3354280Z ##[debug]Installing fastlane...
2020-05-18T05:11:58.3357340Z ##[debug]check path : /usr/local/opt/ruby/bin/gem
2020-05-18T05:11:58.3357900Z ##[debug]gem=/usr/local/opt/ruby/bin/gem
2020-05-18T05:11:58.3363360Z ##[debug]/usr/local/opt/ruby/bin/gem arg: ["install","fastlane"]
2020-05-18T05:11:58.3369790Z ##[debug]exec tool: /usr/local/opt/ruby/bin/gem
2020-05-18T05:11:58.3370260Z ##[debug]Arguments:
2020-05-18T05:11:58.3370800Z ##[debug]   install
2020-05-18T05:11:58.3371190Z ##[debug]   fastlane
2020-05-18T05:11:58.3372500Z [command]/usr/local/opt/ruby/bin/gem install fastlane
2020-05-18T05:11:58.3433100Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3433960Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3434820Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3435610Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3436350Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3437190Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3438000Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3438740Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3439540Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3440330Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3441070Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3441870Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3442650Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3443930Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3444740Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3445520Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3446480Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3447280Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3448060Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3448810Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3449590Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3450370Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3451110Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3451900Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3452770Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3453520Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3454310Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3455100Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3455840Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3456620Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:11:58.3457390Z (node:819) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-05-18T05:15:38.9634540Z Successfully installed google-api-client-0.38.0
2020-05-18T05:15:38.9635620Z Successfully installed fastlane-2.148.0
2020-05-18T05:15:38.9636350Z Parsing documentation for google-api-client-0.38.0
2020-05-18T05:15:38.9637040Z Installing ri documentation for google-api-client-0.38.0
2020-05-18T05:15:38.9637790Z Parsing documentation for fastlane-2.148.0
2020-05-18T05:15:38.9638480Z Installing ri documentation for fastlane-2.148.0
2020-05-18T05:15:38.9639220Z Done installing documentation for google-api-client, fastlane after 214 seconds
2020-05-18T05:15:38.9639610Z 2 gems installed
2020-05-18T05:15:39.1088380Z ##[debug]rc:0
2020-05-18T05:15:39.1089030Z ##[debug]success:true
2020-05-18T05:15:39.1101480Z ##[debug]Updating fastlane...
2020-05-18T05:15:39.1224780Z ##[debug]check path : /usr/local/opt/ruby/bin/gem
2020-05-18T05:15:39.1225330Z ##[debug]gem=/usr/local/opt/ruby/bin/gem
2020-05-18T05:15:39.1226790Z ##[debug]/usr/local/opt/ruby/bin/gem arg: ["update","fastlane","-i","/Users/runner/.gem-cache"]
2020-05-18T05:15:39.1227470Z ##[debug]exec tool: /usr/local/opt/ruby/bin/gem
2020-05-18T05:15:39.1227910Z ##[debug]Arguments:
2020-05-18T05:15:39.1228290Z ##[debug]   update
2020-05-18T05:15:39.1228660Z ##[debug]   fastlane
2020-05-18T05:15:39.1229310Z ##[debug]   -i
2020-05-18T05:15:39.1229970Z ##[debug]   /Users/runner/.gem-cache
2020-05-18T05:15:39.1230810Z [command]/usr/local/opt/ruby/bin/gem update fastlane -i /Users/runner/.gem-cache
2020-05-18T05:15:42.4011730Z Updating installed gems
2020-05-18T05:15:42.4012100Z Nothing to update
2020-05-18T05:15:42.4229680Z ##[debug]rc:0
2020-05-18T05:15:42.4232270Z ##[debug]success:true
2020-05-18T05:15:42.4238090Z ##[debug]fastlaneArguments=--ignore_language_directory_validation true --reject_if_possible true
2020-05-18T05:15:42.4238670Z ##[debug]appIdentifier=com.HIDDEN.HIDDEN
2020-05-18T05:15:42.4240140Z ##[debug]fastlane arg: ["deliver","--force","-u","***","-a","com.HIDDEN.HIDDEN"]
2020-05-18T05:15:42.4241550Z ##[debug]fastlane arg: ["-i","/Users/runner/runners/2.168.2/work/r1/a/HIDDEN/HIDDEN/output/production/iphoneos/Release/Runner.ipa"]
2020-05-18T05:15:42.4242460Z ##[debug]fastlane arg: ["-j","ios"]
2020-05-18T05:15:42.4243170Z ##[debug]fastlane arg: ["--skip_metadata","true"]
2020-05-18T05:15:42.4243950Z ##[debug]fastlane arg: ["--skip_screenshots","true"]
2020-05-18T05:15:42.4245820Z ##[debug]fastlane arg: ["-k","HIDDEN"]
2020-05-18T05:15:42.4252020Z ##[debug]fastlane arg: ["-e","HIDDEN LTD"]
2020-05-18T05:15:42.4255820Z ##[debug]fastlane arg: ["--submit_for_review","true"]
2020-05-18T05:15:42.4256690Z ##[debug]fastlane arg: ["--automatic_release","true"]
2020-05-18T05:15:42.4282960Z ##[debug]fastlane arg: --ignore_language_directory_validation true --reject_if_possible true
2020-05-18T05:15:42.4283660Z ##[debug]exec tool: fastlane
2020-05-18T05:15:42.4284080Z ##[debug]Arguments:
2020-05-18T05:15:42.4284460Z ##[debug]   deliver
2020-05-18T05:15:42.4285100Z ##[debug]   --force
2020-05-18T05:15:42.4285720Z ##[debug]   -u
2020-05-18T05:15:42.4286390Z ##[debug]   ***
2020-05-18T05:15:42.4287040Z ##[debug]   -a
2020-05-18T05:15:42.4287520Z ##[debug]   com.HIDDEN.HIDDEN
2020-05-18T05:15:42.4288160Z ##[debug]   -i
2020-05-18T05:15:42.4288980Z ##[debug]   /Users/runner/runners/2.168.2/work/r1/a/HIDDEN/HIDDEN/output/production/iphoneos/Release/Runner.ipa
2020-05-18T05:15:42.4289800Z ##[debug]   -j
2020-05-18T05:15:42.4290170Z ##[debug]   ios
2020-05-18T05:15:42.4290790Z ##[debug]   --skip_metadata
2020-05-18T05:15:42.4291190Z ##[debug]   true
2020-05-18T05:15:42.4291820Z ##[debug]   --skip_screenshots
2020-05-18T05:15:42.4292230Z ##[debug]   true
2020-05-18T05:15:42.4292830Z ##[debug]   -k
2020-05-18T05:15:42.4293210Z ##[debug]   HIDDEN 
2020-05-18T05:15:42.4293810Z ##[debug]   -e
2020-05-18T05:15:42.4294180Z ##[debug]   HIDDEN LTD
2020-05-18T05:15:42.4294860Z ##[debug]   --submit_for_review
2020-05-18T05:15:42.4295260Z ##[debug]   true
2020-05-18T05:15:42.4295890Z ##[debug]   --automatic_release
2020-05-18T05:15:42.4296290Z ##[debug]   true
2020-05-18T05:15:42.4296960Z ##[debug]   --ignore_language_directory_validation
2020-05-18T05:15:42.4297420Z ##[debug]   true
2020-05-18T05:15:42.4298030Z ##[debug]   --reject_if_possible
2020-05-18T05:15:42.4298450Z ##[debug]   true
2020-05-18T05:15:42.4300200Z [command]fastlane deliver --force -u *** -a com.HIDDEN.HIDDEN -i /Users/runner/runners/2.168.2/work/r1/a/HIDDEN/HIDDEN/output/production/iphoneos/Release/Runner.ipa -j ios --skip_metadata true --skip_screenshots true -k HIDDEN -e HIDDEN LTD --submit_for_review true --automatic_release true --ignore_language_directory_validation true --reject_if_possible true
2020-05-18T05:15:45.3986080Z [05:15:45]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
2020-05-18T05:15:50.0126190Z [05:15:50]: Sending anonymous analytics information
2020-05-18T05:15:50.0126840Z [05:15:50]: Learn more at https://docs.fastlane.tools/#metrics
2020-05-18T05:15:50.0127250Z [05:15:50]: No personal or sensitive data is sent.
2020-05-18T05:15:50.0127670Z [05:15:50]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
2020-05-18T05:15:50.0312600Z 
2020-05-18T05:15:50.0316700Z [!] Could not find option 'env' in the list of available options: username, app_identifier, app_version, ipa, pkg, build_number, platform, edit_live, use_live_version, metadata_path, screenshots_path, skip_binary_upload, skip_screenshots, skip_metadata, skip_app_version_update, force, overwrite_screenshots, submit_for_review, reject_if_possible, automatic_release, auto_release_date, phased_release, reset_ratings, price_tier, app_rating_config_path, submission_information, team_id, team_name, dev_portal_team_id, dev_portal_team_name, itc_provider, run_precheck_before_submit, precheck_default_rule_level, individual_metadata_items, app_icon, apple_watch_app_icon, copyright, primary_category, secondary_category, primary_first_sub_category, primary_second_sub_category, secondary_first_sub_category, secondary_second_sub_category, trade_representative_contact_information, app_review_information, app_review_attachment_file, description, name, subtitle, keywords, promotional_text, release_notes, privacy_url, apple_tv_privacy_policy, support_url, marketing_url, languages, ignore_language_directory_validation, precheck_include_in_app_purchases, app
2020-05-18T05:15:50.0635220Z ##[debug]rc:1
2020-05-18T05:15:50.0635760Z ##[debug]success:false
2020-05-18T05:15:50.0655900Z ##[debug]task result: Failed
2020-05-18T05:15:50.0715990Z ##[error]Error: fastlane failed with return code: 1
2020-05-18T05:15:50.0728640Z ##[debug]Processed: ##vso[task.issue type=error;]Error: fastlane failed with return code: 1
2020-05-18T05:15:50.0731040Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: fastlane failed with return code: 1
```

**Comment by DerGary** [comment] 2020-05-20 13:44
I had the same error. As a workaround I configured the task to install specific version 1.147.0 which still works.

**Comment by nasaleanhorea** [comment] 2020-05-21 07:28
> I had the same error. As a workaround I configured the task to install specific version 1.147.0 which still works.

I believe that was a typo , u meant 2.147.0 right ? We've tried that and it still throws the same error ... this is currently blocking all our releases to the AppStore. Could someone please take care of this issue ?

**Comment by jonsamwell** [comment] 2020-05-21 07:31
@nasaleanhorea I am successfully releasing with version 2.144.0

![image](https://user-images.githubusercontent.com/3694497/82534665-d8993c00-9b88-11ea-8070-9afbaecc2d2b.png)

**Comment by sam-moshenko** [comment] 2020-05-22 03:57
> @nasaleanhorea I am successfully releasing with version 2.144.0
> 
> ![image](https://user-images.githubusercontent.com/3694497/82534665-d8993c00-9b88-11ea-8070-9afbaecc2d2b.png)

Tried the 2.144.0 version, got the same error as OP.

**Comment by DerGary** [comment] 2020-05-23 11:59
@nasaleanhorea you're right that was a typo It is 2.147.0. I configured it with yaml like this:

````
fastlaneToolsVersion: SpecificVersion
fastlaneToolsSpecificVersion: 2.147.0
````

**Comment by sam-moshenko** [comment] 2020-05-25 06:45
For me it seems that the Team Name parameter was the issue. Setting it to empty seems to solve the issue.

![image](https://user-images.githubusercontent.com/9245995/82785962-6a54c200-9e85-11ea-849a-7b37cc7e3441.png)

**Comment by timdoege** [comment] 2020-05-25 07:58
I can not omit the team name, so I tried downgrading to 2.147.0 - seems like the uninstall fails and it uses the agent build-in fastlane (version 2.148.0 atm):
```
2020-05-25T07:48:02.4949830Z ERROR:  While executing gem ... (Errno::ENOENT)
2020-05-25T07:48:02.4968610Z     No such file or directory @ realpath_rec - /Users/runner/.gem-cache
2020-05-25T07:48:02.5089580Z ##[warning]There were errors when trying to uninstall fastlane. Review the error and if required add a script to your pipeline to cleanly uninstall fastlane prior to running this task. Uninstall error: Error: /usr/local/opt/ruby/bin/gem failed with return code: 1
2020-05-25T07:48:02.5103250Z [command]/usr/local/opt/ruby/bin/gem install fastlane -v 2.147.0
2020-05-25T07:51:24.2256570Z Successfully installed google-api-client-0.36.4
2020-05-25T07:51:24.2257570Z Successfully installed fastlane-2.147.0
2020-05-25T07:51:24.2258300Z Parsing documentation for google-api-client-0.36.4
2020-05-25T07:51:24.2258960Z Installing ri documentation for google-api-client-0.36.4
2020-05-25T07:51:24.2259660Z Parsing documentation for fastlane-2.147.0
2020-05-25T07:51:24.2260320Z Installing ri documentation for fastlane-2.147.0
2020-05-25T07:51:24.2261100Z Done installing documentation for google-api-client, fastlane after 196 seconds
2020-05-25T07:51:24.2261490Z 2 gems installed
```
...
```
2020-05-25T07:51:32.4117780Z 
2020-05-25T07:51:32.4122070Z [!] Could not find option 'env' in the list of available options: ... 2020-05-25T07:51:32.4775700Z 
2020-05-25T07:51:32.4776290Z #######################################################################
2020-05-25T07:51:32.4776750Z # fastlane 2.148.1 is available. You are on 2.148.0.
2020-05-25T07:51:32.4777770Z # You should use the latest version.
2020-05-25T07:51:32.4778120Z # Please update using `sudo gem install fastlane`.
2020-05-25T07:51:32.4778540Z #######################################################################
2020-05-25T07:51:32.4779080Z # Run `sudo gem cleanup` from time to time to speed up fastlane
2020-05-25T07:51:32.4779590Z #######################################################################
```

**Comment by SEGVeenstra** [comment] 2020-05-28 13:59
> I can not omit the team name, so I tried downgrading to 2.147.0 - seems like the uninstall fails and it uses the agent build-in fastlane (version 2.148.0 atm):
> 
> ```
> 2020-05-25T07:48:02.4949830Z ERROR:  While executing gem ... (Errno::ENOENT)
> 2020-05-25T07:48:02.4968610Z     No such file or directory @ realpath_rec - /Users/runner/.gem-cache
> 2020-05-25T07:48:02.5089580Z ##[warning]There were errors when trying to uninstall fastlane. Review the error and if required add a script to your pipeline to cleanly uninstall fastlane prior to running this task. Uninstall error: Error: /usr/local/opt/ruby/bin/gem failed with return code: 1
> 2020-05-25T07:48:02.5103250Z [command]/usr/local/opt/ruby/bin/gem install fastlane -v 2.147.0
> 2020-05-25T07:51:24.2256570Z Successfully installed google-api-client-0.36.4
> 2020-05-25T07:51:24.2257570Z Successfully installed fastlane-2.147.0
> 2020-05-25T07:51:24.2258300Z Parsing documentation for google-api-client-0.36.4
> 2020-05-25T07:51:24.2258960Z Installing ri documentation for google-api-client-0.36.4
> 2020-05-25T07:51:24.2259660Z Parsing documentation for fastlane-2.147.0
> 2020-05-25T07:51:24.2260320Z Installing ri documentation for fastlane-2.147.0
> 2020-05-25T07:51:24.2261100Z Done installing documentation for google-api-client, fastlane after 196 seconds
> 2020-05-25T07:51:24.2261490Z 2 gems installed
> ```
> 
> ...
> 
> ```
> 2020-05-25T07:51:32.4117780Z 
> 2020-05-25T07:51:32.4122070Z [!] Could not find option 'env' in the list of available options: ... 2020-05-25T07:51:32.4775700Z 
> 2020-05-25T07:51:32.4776290Z #######################################################################
> 2020-05-25T07:51:32.4776750Z # fastlane 2.148.1 is available. You are on 2.148.0.
> 2020-05-25T07:51:32.4777770Z # You should use the latest version.
> 2020-05-25T07:51:32.4778120Z # Please update using `sudo gem install fastlane`.
> 2020-05-25T07:51:32.4778540Z #######################################################################
> 2020-05-25T07:51:32.4779080Z # Run `sudo gem cleanup` from time to time to speed up fastlane
> 2020-05-25T07:51:32.4779590Z #######################################################################
> ```

Same for me, the suggestion tells me I could try to run a script before this task to remove it myself. But it seems to not allow me doing so.

**Comment by DerGary** [comment] 2020-05-28 14:25
I just configured the tool version and the task removed the fastlane on its own and reinstalled the old version. Maybe it depends on a specific MacOs Version? I am using our own on premise macs with mac os Catalina version 10.15.3. I didn't tried hosted macs. Maybe this helps.

Greetings Gary

**Comment by timdoege** [comment] 2020-05-28 18:04
Hm, I removed the "Install fastlane" option (under advanced) and the hosted agent states fastlane version `2.144.0` under "Details":
```
Tools
- Fastlane 2.144.0
- Cmake 3.17.0
- App Center CLI 1.2.2
- Azure CLI 2.2.0
- AWS CLI 2.0.5
```

(agent version `2.168.2`)
but I still get the 
````
[!] Could not find option 'env' in the list of available options:
```
error which seems ... odd.

I can't see any option to choosing a specific Mac OS version from the agent pool, though.

**Comment by dattakadiyala** [comment] 2020-05-29 16:06
I have the same issue, but I am using Microsoft hosted Mac agents, so when i try to set a specific version of fast lane, it tries to uninstall the latest version and fails.
Has any one got a way around this issue?

@madhurig @ lkillgore : app-store-vsts-extension basically fails for production lane for all using Microsoft hosted Mac agents as they have Fastlane 2.148.1 installed and when trying to use specific version of fast lane form advanced settings will also fail when uninstalling current version of fast lane.

**Comment by paulburz** [comment] 2020-05-29 16:08
> For me it seems that the Team Name parameter was the issue. Setting it to empty seems to solve the issue.
> 
> ![image](https://user-images.githubusercontent.com/9245995/82785962-6a54c200-9e85-11ea-849a-7b37cc7e3441.png)

This works for us. With the latest version of Fastlane.

**Comment by dattakadiyala** [comment] 2020-05-29 16:35
Thanks @paulburz I had to remove the Team Name and instead used Team Id  to fix this issue `Could not find option 'env' in the list of available options` as I have different Appstore Connect accounts linked.

**Comment by timdoege** [comment] 2020-05-29 18:24
Great - using the Team Id instead of the Team Name field works for me.

**Comment by girardimatthew** [comment] 2020-08-20 13:07
Does anyone have any updates on this issue ? 
I'm still getting this error with the latest fastlane version.

**Comment by DerGary** [comment] 2020-08-20 13:23
@girardimatthew  With the newest version and using the Team Id instead of the team name, it works for me. I previously supplied both team id and team name, but only supplying team id works as suggested by @timdoege

**Comment by girardimatthew** [comment] 2020-08-20 13:30
Thanks @DerGary I'll try as you suggested!

**Comment by girardimatthew** [comment] 2020-08-21 06:41
@DerGary Actually I haven't tried what you suggests here: [comment-677662191](https://github.com/microsoft/app-store-vsts-extension/issues/152#issuecomment-677662191)
because it works using fastlane 2.147.0, as you said here: [comment-631482752](https://github.com/microsoft/app-store-vsts-extension/issues/152#issuecomment-631482752)

**Comment by girardimatthew** [comment] 2020-09-04 18:25
@anatolybolshakov 
Does "awaiting deployment" mean that the fix provided by @alexander-smolyakov  will be released pretty soon ?

**Comment by anatolybolshakov** [comment] 2020-09-07 07:48
Hi @girardimatthew, yep, we are going to release changes this week, so once we will remove this label - these changes will be deployed

**Comment by girardimatthew** [comment] 2020-09-07 10:22
that sounds great! thank you ! 🙂

**Comment by alexander-smolyakov** [comment] 2020-09-14 07:33
The release with the fix was published, I'm closing it at the moment - feel free to reopen if the issue is still reproducible.

**Closed by alexander-smolyakov** 2020-09-14 07:33 UTC
Labels: Task: AppStoreRelease, bug
